### ISSUE TITLE
No longer able to publish Gradle plugin because of wrong "Invalid plugin ID 'plugins'"

### ISSUE THREAD

**Issue by LouisCAD** [gradle/plugin-portal-requests#1]
I'm trying to publish the plugin in the `plugin` module of [that project](https://github.com/LouisCAD/Splitties/tree/8393464c61d6b0f180d05b8c4971d957be8f2305)
which as its `build.gradle.kts` [here](https://github.com/LouisCAD/Splitties/blob/8393464c61d6b0f180d05b8c4971d957be8f2305/plugin/build.gradle.kts).
I already published a version of a previous revision successfully on the Gradle portal.

I'm running that command: `./gradlew :plugin:publishPlugins`.

### Expected Behavior
Just like previous versions, I can publish my plugin smoothly on the Gradle portal as long as the version doesn't already exist.

### Current Behavior
Getting that error at build time:
```
* What went wrong:
Execution failed for task ':plugin:publishPlugins'.
> Invalid plugin ID 'plugins': Plugin IDs should be namespaced, e.g. 'com.example.plugins'
```

### Context
That's preventing me from publishing a new version of my Gradle plugin.

### Steps to Reproduce
Clone [the affected revision of the project](https://github.com/LouisCAD/Splitties/tree/8393464c61d6b0f180d05b8c4971d957be8f2305), and run `./gradlew :plugin:publishPlugins`.

### Your Environment
I'm using macOS 10.14.6.

**Comment by lacasseio** [comment]
@LouisCAD Thanks for bringing this to our attention. This is indeed the right place to raise such issues moving forward. Congrats for being the first! 🎉Let me look at this a bit more.

**Comment by lacasseio** [comment]
It seems to be there were no issue on the Plugin Portal side from what I understood about the request. Let's close it and open another one if you have another issue.
