### ISSUE TITLE
Plugin 'com.github.turansky.yfiles'. Remove request for versions '0.0.15' & '0.0.18'

### ISSUE THREAD

**Issue by turansky** [gradle/plugin-portal-requests#10]
### Plugin Id
`com.github.turansky.yfiles`

### Current Plugin Owner
`turansky`

### Context
Remove please following versions of plugin:
* `0.0.15`
* `0.0.18`

**Comment by lacasseio** [comment]
I see you have a version superseding those two versions. It's ok to have unsupported plugin versions. The better alternative would be a feature request regarding ways to mark the plugin as unsupported.
