### ISSUE TITLE
Approve new plugins and remove these old

### ISSUE THREAD

**Issue by zero88** [gradle/plugin-portal-requests#100]
### Plugin Id

I would like remove these plugins:

- `io.github.zero88.qwe.gradle.app`
- `io.github.zero88.qwe.gradle.docker`
- `io.github.zero88.qwe.gradle.oss`
- `io.github.zero88.qwe.gradle.root`

### Current Plugin Owner

@zero88

### Context

Before, I organized my plugins in my Github account, but now I moved to my organization https://github.com/play-iot/gradle-plugin.
I tried to push these plugins with old id, but still pending approval. After that, I changed these to new id (for better name/purpose also):
- `io.github.zero88.gradle.oss`
- `io.github.zero88.gradle.qwe.app`
- `io.github.zero88.gradle.qwe.docker`
- `io.github.zero88.gradle.root`

**One Question**
Is any way to increase this process, make it more automation?
it takes too long time to approval. So much pain, because I depend heavily on CI system.
Actually, I tried to release on Nexus OSSRH also, but it is not success because plugin descriptor is missing too much required fields, such as `Project URL missing, License information missing, SCM URL missing, Developer information missing`

**Comment by ljacomet** [comment]
Answered the migration aspect over email.

The policy is not to remove plugins as it could break builds - closing
