### ISSUE TITLE
Transfer ownership of com.bakdata.sonar and com.bakdata.sonatype

### ISSUE THREAD

**Issue by AHeise** [gradle/plugin-portal-requests#101]
### Plugin Id

https://plugins.gradle.org/plugin/com.bakdata.sonar
https://plugins.gradle.org/plugin/com.bakdata.sonatype

### Current Plugin Owner

me

### Expected Plugin Owner

https://plugins.gradle.org/u/bakdata-bot

### Context

I left the company a while ago and now we noticed that some important infrastructure still depends on my credentials.

**Comment by ljacomet** [comment]
This is now done
