### ISSUE TITLE
Unintended approval process for subsequent versions of existing Gradle Plugins

### ISSUE THREAD

**Issue by jkasten2** [gradle/plugin-portal-requests#103]
### Expected Behavior
Submitting an update to an existing live Gradle Plugin should immediately take effect, without requiring an approval. If this is a new requirement this should be documented.

### Current Behavior
Running `./gradlew publishPlugins` to publish an update to an existing plugin shows the following message:
```
> Task :publishPlugins
Publishing plugin com.onesignal.androidsdk.onesignal-gradle-plugin version 0.13.0
Thank you. Your new plugin com.onesignal.androidsdk.onesignal-gradle-plugin has been submitted for approval by Gradle engineers. The request should be processed within the next few days, at which point you will be contacted via email.
```

Viewing the plugin on https://plugins.gradle.org/ also shows the "Pending Approval" status for the update.
![image](https://user-images.githubusercontent.com/645861/121427436-91afed00-c929-11eb-8e29-1c7075d59f0b.png)

### Context
Per the Gradle Plugin Portal documentation and other replies subsequent versions of existing Gradle Plugins should not require an approval.

From the official Gradle blog ["Gradle Plugin Portal Approval Policy Update"](https://blog.gradle.org/new-plugin-portal-acceptance-criteria)
> Gradle is updating the plugin approval policy for plugins submitted to the Gradle Plugin Portal, effective today, to begin adding stronger security safeguards for plugin consumers.
First off, this does not affect plugins already on the plugin portal, just new plugins. Gradle builds that use plugins will not be affected in any way.
....
These checks do not yet apply for subsequent versions of a given plugin, and aren’t yet going to be retroactively enforced.

[From](https://github.com/gradle/plugin-portal-requests/issues/69#issuecomment-725568680
) @JLLeitschuh (a member of Gradle)
> Subsequent versions will not require approval.

I was not able to find any more recent official information on this than the blog from Oct. 2018 and the reply from Gradle on Nov. 2020, both listed above. The last time I submitted an update to the Gradle Plugin Portal was December 12, 2020 which did not require an approval.

### Your Environment
* Gradle 7.0.2
*  id 'com.gradle.plugin-publish' version '0.11.0'

### Related Issues
* https://discuss.gradle.org/t/publishing-existing-plugin-org-gretty-plugin-org-gretty-has-been-submitted-for-approval-by-gradle-engineers/39457

**Comment by jkasten2** [comment]
## Issue - Group Silently Changed
I found my issue was the `group` for my plugin changed from under me.  The prefix `gradle.plugin` was no longer by automatically added to the `group` property per the Gradle Plugins [`publish-plugin`](https://plugins.gradle.org/docs/publish-plugin) docs:
> By default, the publishing plugin will use the project group, prefixed with `gradle.plugin` ...

## What changed
The only changes I could see changing this default prefix behavior is the following:
* Upgraded from Gradle 6.7.1 to Gradle 7.0.2
* Added `id 'maven-publish'`
* `id 'com.gradle.plugin-publish' version '0.11.0'` - This didn't change, just declaring the version used.

## Documentation 
I was not able to find any documentation on this `group` prefixing behavior change. Is there something I overlooked in the Gradle documentation?

## Recommendations to the Gradle team
### Show Group for Plugin
I had no idea that the generated `group` for my plugin changed and this wasn't indicated with the `publishPlugins` Gradle task nor was on the Gradle Plugin Portal dashboard (https://plugins.gradle.org/ ). I would recommend Gradle add the "group" to both these locations to help provide future issues like this.

**Comment by ljacomet** [comment]
Indeed this is a consequence of leveraging the integration with the `maven-publish` plugin. And this information is also lacking in the documentation. We are hoping to be able to publish updated documentation and rules for plugin approvals in the coming weeks.

Note that we are moving away from having `gradle.plugin` as the group prefix since this prevents parallel publication on Maven Central for example.

So if you ever want to perform that migration, let us know so we can speed up the one time approval it will trigger.
