### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by dmdashenkov** [gradle/plugin-portal-requests#104]
Could you please take a look at our new [plugin](https://plugins.gradle.org/plugin/io.spine.proto-data)?

It's published by my organization. We have already got [another Gradle plugin](https://plugins.gradle.org/plugin/io.spine.tools.gradle.bootstrap) approved and functioning for quite some time.

Also, we've uploaded a few versions of the new plugin, and, at some point, having realized a copy-paste-related error, changed the plugin description. Not sure if this relates to #103, just thought I'd let you know this fact.

**Comment by jkasten2** [comment]
@dmdashenkov I don't believe this is related to my #103 issue as you're uploading a new plugin, not updating an existing one. See Gradle's ["Gradle Plugin Portal Approval Policy Update"](https://blog.gradle.org/new-plugin-portal-acceptance-criteria) blog post for reference:
> Gradle will check the following for new plugins submitted to plugins.gradle.org:
> * Description and project URL are valid and not misleading
> * The group ID and artifact ID are valid and not misleading

**Comment by dmdashenkov** [comment]
The plugin has been approved, thanks.
