### ISSUE TITLE
Spring Boot Thin Launcher Plugin

### ISSUE THREAD

**Issue by dsyer** [gradle/plugin-portal-requests#105]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishExisting'.
> Failed to post to server.
  Server responded with:
  The user does not have permission to create a new plugin with ID: org.springframework.boot.experimental.thin-launcher

```

### Plugin Id
org.springframework.boot.experimental.thin-launcher

### Current Plugin Owner
No idea. It was published via Bintray before that shut down.

### Expected Plugin Owner
Account ID "spring"

### Context
Bintray migration. This plugin doesn't show up as "reclaimable" in the account profile.

**Comment by ljacomet** [comment]
Plugin has been associated with the Spring user, see https://plugins.gradle.org/plugin/org.springframework.boot.experimental.thin-launcher
