### ISSUE TITLE
Please Transfer com.contrastsecurity.contrastplugin from gmoore to gilday

### ISSUE THREAD

**Issue by gmoore** [gradle/plugin-portal-requests#106]
### Plugin Id

https://plugins.gradle.org/plugin/com.contrastsecurity.contrastplugin

### Current Plugin Owner

gmoore

### Expected Plugin Owner

gilday

### Context

I have left Contrast Security. Please transfer ownership to `gilday`

Thanks!

**Comment by ljacomet** [comment]
This is now done

**Comment by gilday** [comment]
Thank you!
