### ISSUE TITLE
Cannot activate account

### ISSUE THREAD

**Issue by EricSalemi** [gradle/plugin-portal-requests#107]
Hi,

Few days ago I attempted to create an account on the Gradle plugin portal (guardsquare-ci@guardsquare.com).

Activation email was never received because the inbox did not exist yet.

After the inbox was created I tried to reset the password in an attempt to receiver the activation email again... no success so far.

How can I activate the account?
Can the activation email be resent?

Would be nice to have that option available from the Gradle portal.

**Comment by EricSalemi** [comment]
As a workaround I registered another account with a different username/email:

username: guardsquare-ci
email: guardsquare.ci@guardsquare.com

I would rather have everything under the `guardsquare` username so let me know what is possible.

**Comment by ljacomet** [comment]
User `guardsquare` has been activated.
