### ISSUE TITLE
publish plugin error

### ISSUE THREAD

**Issue by godfather1103** [gradle/plugin-portal-requests#109]
### Expected Behavior

publish plugin error, server responded exists but not found
```
 Server responded with:
  Plugin: 'io.github.godfather1103.gradle-base-plugin', version: '1.4' exists already. It was created: 2021-07-01 05:47:16.13
```

**Comment by godfather1103** [comment]
<img width="1150" alt="iShot2021-07-01 14 11 31" src="https://user-images.githubusercontent.com/11797964/124075165-097bbe00-da77-11eb-9581-de49fdbf7c58.png">
<img width="1330" alt="iShot2021-07-01 14 14 58" src="https://user-images.githubusercontent.com/11797964/124075176-0ed90880-da77-11eb-9286-eccb9cc6ec2a.png">

**Comment by ljacomet** [comment]
Version 1.4 was published around July 1st and is marked as "Disabled" in the database. It looks like something interrupted the publication and caused this invalid state.

I also see that 1.4.2 has been published since then. I am going to close this issue as a newer version is now available.

**Comment by godfather1103** [comment]
ok
