### ISSUE TITLE
Transfer ownership of  org.gosu-lang.gosu plugin

### ISSUE THREAD

**Issue by sadheeshv** [gradle/plugin-portal-requests#110]
###Summary
Hi, 
Guidewire is managing an open source project "Gradle-gosu-plugin" which is a gradle plugin for Gosu -Guidewire's open source JVM language.
The person who developed this plugin is no longer with GW and currently I'm managing this project for past two years. Bintray was our primary distribution platform until it became sunset. Now we'd like to publish back to Gradle plugin portal.

### Plugin Id 
org.gosu-lang.gosu

website = 'http://gosu-lang.org'
vcsUrl = 'https://github.com/gosu-lang/gradle-gosu-plugin'

### Current Plugin Owner
Kyle Moore

### Expected Plugin Owner
Sadheesh Venkatachalam
Plugin portal account username: gwgosuplugin

### Context
https://github.com/gosu-lang/gradle-gosu-plugin/commits/g-master

**Comment by DPUkyle** [comment]
SGTM!

**Comment by sadheeshv** [comment]
Thank you! Kyle

**Comment by ljacomet** [comment]
This has been done: https://plugins.gradle.org/plugin/org.gosu-lang.gosu
