### ISSUE TITLE
Transfer ownership of ml-gradle plugin

### ISSUE THREAD

**Issue by rjrudin** [gradle/plugin-portal-requests#112]
### Plugin Id

com.marklogic.ml-gradle - https://plugins.gradle.org/plugin/com.marklogic.ml-gradle 

### Current Plugin Owner

rjrudin (me)

### Expected Plugin Owner

marklogic - https://plugins.gradle.org/u/marklogic

### Context

I am an employee of MarkLogic and need to transfer ownership to our organization so I'm not a single point of failure here.

**Comment by ljacomet** [comment]
This is now done - https://plugins.gradle.org/plugin/com.marklogic.ml-gradle
