### ISSUE TITLE
[com.gradle.plugin-publish] add task to validate configuration

### ISSUE THREAD

**Issue by anatawa12** [gradle/plugin-portal-requests#113]
Currently, `publishPlugins` task can be failed with missing plugin configuration (like display name) errors. However, it looks no way to know those errors without side effects.

### Expected Behavior

There's some task to know some missing configuration for publishing to Gradle Plugin Portal. this task should be dependencies of `check` I think.

### Current Behavior

There's some way to know missing configuration errors without side effects.

**Comment by ov7a** [comment]
Since 1.2.0, you [can](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#publish_to_the_plugin_portal) use `--validate-only` option to `publishPlugins` task to get feedback from server-side plugin validation without actually publishing.
