### ISSUE TITLE
Changing my email address

### ISSUE THREAD

**Issue by c1phercraft** [gradle/plugin-portal-requests#114]
Hey,

I need to change my email address but there is no option in my account settings. In the forums I'm told to log an issue for that here.

The new address needs to be: `ingo+gradle@freedom.nl`.

Cheers,
Ingo

**Comment by ljacomet** [comment]
Hello,

Sure but could you indicate which user this is about?

Note that depending on the user being through GitHub or not, we may need to validate this change through an email exchange first.

**Comment by c1phercraft** [comment]
Nevermind. I found a way. Thanks for responding!
