### ISSUE TITLE
Provide more details about the ownership model

### ISSUE THREAD

**Issue by martinbonnin** [gradle/plugin-portal-requests#117]
I recently got an error trying to publish a new plugin with user1:

```
The user 'foo' does not have write permissions to plugin 'com.example.bar'
```

Trying to use another user (user2) gives me this error:

```
The group ID XYZ is not owned by your user.
```

Can you share more details about how to fix those? If the group is owned by user1, how come they are not able to create a new plugin?

**Comment by ljacomet** [comment]
Hi,

Plugin ownership consist of two things:
* Owning the plugin ID
* Owning the Maven group used by the plugin artifact

A user needs to own both.
Example with the Gradle [build scan plugin](https://plugins.gradle.org/plugin/com.gradle.build-scan):
* Plugin ID: `com.gradle.build-scan`
* Maven Group: `com.gradle`

If you have specific questions for a given plugin / group / owner, you can reach out at plugin-portal-support@gradle.com

**Comment by martinbonnin** [comment]
Thanks for the quick response. My current understanding is that:

* The plugin ID owner is the user that publishes the first version of the plugin
* The Maven Group owner is the user that publishes the first plugin that has this Maven Group

I happen to be stuck on publishing pluginId `com.gradleup.gr8` because the Maven Group owner doesn't have rights to publish the pluginId. My current guess is that the pluginId was "registered" because it's proxied from Jcenter (which itself mirrored it from MavenCentral). Is that possible? How can I fix this?

**Comment by ljacomet** [comment]
This is a new plugin right?
What's the Maven group Id you intended to use?
Currently `com.gradleup.gr8` is owned by https://plugins.gradle.org/u/mbonnin

It might be a failed publication that's causing the portal to be in a bad state for this specific combination.

**Comment by martinbonnin** [comment]
> This is a new plugin right?

Correct

> What's the Maven group Id you intended to use?

Group Id: `com.gradleup`
Gav coordinates: `com.gradleup:gr8-plugin:0.2`
Plugin Id: `com.gradleup.gr8`

My user (mbonnin) owns id `com.gradleup.gr8` but I believe someone else owns group `com.gradleup` so maybe that's the issue?

**Comment by ljacomet** [comment]
Indeed, `com.gradleup` is owned by https://plugins.gradle.org/u/tasomaniac

Let me know if we should attempt to resolve that ownership issue.

**Comment by martinbonnin** [comment]
Can you transfer `com.gradleup.gr8` to @tasomaniac ? We'll share the credentials in CI.

**Comment by ljacomet** [comment]
This is now done.

Please confirm once you have been able to deploy a version.

**Comment by martinbonnin** [comment]
Works like a charm, thanks!
