### ISSUE TITLE
Transfer ownership of com.ca.apim.gateway plugins

### ISSUE THREAD

**Issue by hydak** [gradle/plugin-portal-requests#118]
### Plugin Id
- com.ca.apim.gateway.gateway-developer-plugin
- com.ca.apim.gateway.gateway-developer-plugin-base
- com.ca.apim.gateway.gateway-export-plugin
- com.ca.apim.gateway.gateway-export-plugin-base
- com.ca.apim.gateway.gateway-import-base
- com.ca.apim.gateway.gateway-import-plugin
- com.ca.apim.gateway.gateway-policy-plugin
- com.ca.apim.gateway.gateway-policy-plugin-base
- com.ca.apim.gateway.modular-assertion-builder
### Current Plugin Owner
Christopher Hydak - hydak

### Expected Plugin Owner
Scott Chang - scottchc1

### Context
I am leaving the company that publishes these plugins and wish to transfer them to my successor

**Comment by ljacomet** [comment]
This is now done
