### ISSUE TITLE
Specified tags are omitted from the published plugin's portal page

### ISSUE THREAD

**Issue by lingocoder** [gradle/plugin-portal-requests#12]
### Expected Behavior

I expected that all tags listed in my plugin's publishing metadata would appear on the plugin's portal page. 

### Current Behavior

An unlucky number of only thirteen of the tags I specified in the metadata appear on the plugin's portal page.

### Context

The [*Configure the Plugin Publishing Plugin*](http://bit.ly/pubNbDamd) section of the user guide talks about tags.  The [*How do I use the Plugin Publishing Plugin?*](http://bit.ly/plugPubPlug) also talks about tags. Neither of those documents define any specific limit on the number of tags that can be used.

The *`pluginBundle`* block of the build script I use to publish *[the com.lingocoder.mrjar plugin](https://bit.ly/mrJar)* lists twenty-two tags. Each tag represents the capabilities ***mrJar*** provides.  The intent is to make it easier for users to find the capabilities they would be looking for.

In the absence of any explicitly-defined limit to the number of tags allowed — *nor any publicly-defined character limit* — it's reasonable to expect that all the publishing metadata I specify, would be used.
 
### How has this issue affected you?

The original content of the [*Building Java 9 Modules*](http://bit.ly/BldJ9Guide) section of the user guide has recently been removed. In its place is a tag-filtering, query-stringed link that refers readers to the plugin portal. Because the tag that that search query uses, is one of the tags that was omitted from my plugin's published metadata, users looking for the *JPMS* capability that my plugin provides, will not see ***mrJar*** on the page that the user guide refers them to.

### Steps to Reproduce 

1. Visit the [*Building Java 9 Modules*](http://bit.ly/BldJ9Guide) section of the user guide
2. Click on the [*„Some community plugins“ referral link*](http://bit.ly/jpmsQuery)... 
3. Note that the results that listed are incomplete.

### Your Environment

***N.A.***

**Comment by lacasseio** [comment]
Thanks for the request, I can confirm the backend only contains 13 tags. I will start poking around to see how sets this limit. There is no reason for having this limit aside from avoiding UX weirdness but it isn't the case. Could you confirm the tags you are seeing on the plugin portal are from the original publication to the portal or did you add some tags and they used to appear with new versions until you reached 13 tags?

**Comment by lacasseio** [comment]
It looks like the tags aren't being updated for new version. Could you tell us what are the new tags? I unfortunately couldn't quickly find your plugin code to proceed with the update.

**Comment by lingocoder** [comment]
Hi @lacasseio,

Thank you for looking into this.

> „...*Could you confirm the tags you are seeing on the plugin portal are from the original publication to the portal*...“

Yes. I just checked *`v0.0.1`* in the project's repository and I've confirmed that the same tags that are appearing in the portal right now (*`v0.0.15`*) are the same thirteen that were originally published on September 2, 2019.

> „...*Could you tell us what are the new tags?*...“

I can do better than that :) Here is the very code block that I used for the last publication I pushed (*`v0.0.16`*):

```
...
pluginBundle {
    website = 'http://lingocoder.com/mrjar'
    vcsUrl = 'https://github.com/lingocoder/mrjar/'
    description = 'Adds easy JPMS module creation capabilities to Gradle. Enhances Buildship/Eclipse with JPMS modularity. Easy Multi-Release JAR File assembly'
    tags = ['jpms', 'modules', 'mrjar', 'modular', 'multi-release', 'jigsaw', 'gradle-modules-plugin', 'java9', 'modularity']

    plugins {
        mrjar {
            // id is captured from java-gradle-plugin configuration
            displayName = 'Modular MRJAR Files Made Easy'
        }
    }
}
...
```

Might [*the recent deleting of `v0.0.16`*](https://github.com/gradle/plugin-portal-requests/issues/15) have screwed up my tags somehow?

Sincere thanks for you help on this, lacasseio 👍

**Comment by lacasseio** [comment]
Thanks for your patience, your tags should be updated now.

**Comment by lingocoder** [comment]
Thank you lacasseio,

Will I need to submit requests each time I might want to update the tags?

**Comment by lacasseio** [comment]
Unfortunately this is the only way to do it at the moment. I suggest you open a feature request so everyone can vote on.
