### ISSUE TITLE
Transfer ownership of org.jetbrains.compose

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [gradle/plugin-portal-requests#123]
We want to transfer ownership of `org.jetbrains.compose` plugin
from the account tied to the work email of https://github.com/olonho
to the team account of JetBrains Compose.

### Plugin Id
org.jetbrains.compose

### Current Plugin Owner

https://plugins.gradle.org/u/jb-compose-dev

### Expected Plugin Owner

https://plugins.gradle.org/u/jb-compose

### Context

Reasons for transfer:
* Use JetBrains Compose logo instead of the project's lead photo.
* Avoid dependency on a person's work email identity 
(which might become unavailable e.g. if a person leaves the company).

**Comment by jbartok** [comment]
Done.
