### ISSUE TITLE
Existing Plugin needs activation

### ISSUE THREAD

**Issue by Larusso** [gradle/plugin-portal-requests#124]
### Context
I wanted to publish a new version of my plugin. I changed my setup to leverage the `java-gradle-plugin` in combination with `com.gradle.plugin-publish`. In the past I only used the `com.gradle.plugin-publish` plugin and created the properties file etc by hand. I also added two new plugins in the same project which I also wanted to publish.
I was always fine with the fact that all my plugins where put in the `gradle.plugin.*` group.
From the output of my build this seems to be no longer the case?
I received two emails with inforamtion that a new version has been published (`net.wooga.plugins` and `net.wooga.plugins-private`). But I can't find and resolve them on the plugins portal page.

I'm confused if now all new plugins need to be approved before going live. I could not find a reference with the approval process in the docs. But I was under the assumption that one needed approval only if one wants to publish with a custom group name (without `gradle.plugins.` appended)

```
> Task :publishPlugins

Publishing plugin net.wooga.plugins-local version 3.0.0-rc.1

Thank you. Your new plugin net.wooga.plugins-local has been submitted for approval by Gradle engineers. The request should be processed within the next few days, at which point you will be contacted via email.

Publishing plugin net.wooga.plugins version 3.0.0-rc.1
Publishing plugin net.wooga.plugins-private version 3.0.0-rc.1
Publishing artifact build/libs/atlas-plugins-3.0.0-rc.1.jar
Publishing artifact build/libs/atlas-plugins-3.0.0-rc.1.jar
Publishing artifact build/publications/pluginMaven/pom-default.xml
Publishing artifact build/publications/pluginMaven/module.json
Activating plugin net.wooga.plugins-local version 3.0.0-rc.1
Activating plugin net.wooga.plugins version 3.0.0-rc.1
Activating plugin net.wooga.plugins-private version 3.0.0-rc.1
```

**Comment by jbartok** [comment]
Hi. Plugins usually need approval only on the initial publication (first version) or when their GAV coordinates change. I think that's the case now, will look into it and let you know.

**Comment by jbartok** [comment]
@Larusso The cause for the approval is indeed that the plugin publication GAV has lost the 'gradle.plugin' prefix. That probably happened because you included the Maven Publish plugin or have added a `mavenCoordinates` block to override the GAV. I haven't dug through the commit history, but I think it's the former. 

I have approved your plugins and I don't think you will need to go through approval again on the next version, if you don't change the publication again.

**Comment by Larusso** [comment]
@jbartok thanks for the super fast reply.
I think this is actually playing well into my cards because even though I never minded the group change in the past It would be better if I can keep my `mavenCordinates`. This plugin or better these 3 plugins are the base for our internal plugins. So I guess If I use this plugin for publishing all our other plugins these would then also change the maven coordinates and would need an activation/approval. That is fine by me. This helps us with local development since we always had to adjust the dependency groupname when testing local snapshots or working with `includeBuild`.

Thanks again.
