### ISSUE TITLE
Deletion of "prevent-dev" account (contains no plugins)

### ISSUE THREAD

**Issue by alexander-schmidt** [gradle/plugin-portal-requests#127]
### Plugin Id
none (see below)

### Current Plugin Owner
none (see below)

### Context
I kindly request deletion of the account "prevent-dev" (email "opensource@preventgroup.com"). No plugins were published from the account yet, and none will ever be.

The "prevent-dev" account is merely a remnant of a failed attempt to submit our first release of the [SoftiCAR Gradle Plugins](https://github.com/softicar/gradle-plugins) (prefix `com.softicar.gradle.*`).

We found that it's easier for everybody if we just use the "softicar" brand (which is a trademark of Prevent DEV GmbH, Germany) as an account name. We hence created a _new_ "softicar" account (email "opensource@softicar.com") to supersede the "prevent-dev" account.

So, as a cleanup measure, I hereby request removal of the abandoned "prevent-dev" account.

Kind regards and thanks in advance,

Alexander Schmidt
SoftiCAR System Architect
Prevent DEV GmbH, Wolfsburg, Germany

**Comment by ljacomet** [comment]
Done
