### ISSUE TITLE
Transfer ownership of edu.umich.med.michr.h2-plugin

### ISSUE THREAD

**Issue by gunalmel** [gradle/plugin-portal-requests#128]
The ownership of edu.umich.med.michr.h2-plugin plugin from is tied to https://github.com/HipDragon who was working at
Michigan Institute for Clinical and Health Research (MICHR) at the University of Michigan. He left work and we are not able to publish the updated version of the plugin we use with our applications. We like to transfer the ownership to the team account of MICHR developers. 

### Plugin Id
edu.umich.med.michr.h2-plugin

### Current Plugin Owner
Joshua Raymond 
https://github.com/HipDragon

### Expected Plugin Owner
Michigan Institute for Clinical and Health Research (MICHR) at the University of Michigan
michr-developers \<michr-developers@med.umich.edu\>

### Context
We don't like to lose access to updating plugin when an employee leaves.
Use MICHR logo instead of the project's main developer's photo who's now a former employee.

**Comment by ljacomet** [comment]
Any chance we can have @hipdragon confirm this?

This would help confirm the validity of this request.

**Comment by ljacomet** [comment]
Asking as the code source for this plugin is not public - at least I cannot view https://github.com/umich-michr/h2-plugin - which means it is impossible to confirm from GH users and commits that the request is valid.

Though I could find the following repository: https://github.com/umich-michr/h2-gradle-plugin which looks like the plugin and has you and HipDragon as committers.

Maybe that should be updated as well, correct?

**Comment by gunalmel** [comment]
Yes, the source code is at https://github.com/umich-michr/h2-gradle-plugin and that needs to be corrected as well. Nobody touched the code here since HipDragon left last year.

I emailed HipDragon with the link to this ticket but would the information at https://github.com/umich-michr/h2-gradle-plugin be not enough to make the change? The repo is owned by 
Michigan Institute for Clinical & Health Research organization and the members are the current developers.

**Comment by ljacomet** [comment]
Changes have been done, including updating the GH link.
See https://plugins.gradle.org/plugin/edu.umich.med.michr.h2-plugin
