### ISSUE TITLE
Transfer ownership of com.betterme.eventsdroid & com.betterme.localizer plugins

### ISSUE THREAD

**Issue by constmikhailovskiy** [gradle/plugin-portal-requests#129]
The ownership of both com.betterme.eventsdroid & com.betterme.localizer plugins are tied to my own account, but it would be more appropriate and reliable to transfer them to the corresponding account of the orgranization who owns these plugins.

**Plugin Ids**

com.betterme.eventsdroid
com.betterme.localizer 

**Current plugins owner**

Konstantin Mikhailovskiy (Android Tech Lead at BetterMe)
Github: https://github.com/constmikhailovskiy
Gradle plugins: https://plugins.gradle.org/u/Kostyantyn

**Expected plugins owner**

BetterMe: https://github.com/betterme-dev/
Gradle plugins: https://plugins.gradle.org/u/AndroidDev (dev.android@betterme.world)

**Context**

As these plugins are developed, maintained and also used in projects developed by the whole Android team at BetterMe, it would be more appropriate and secure to transfer the ownership of these plugins to the organization itself rather than having me as one of the team members & contributors tied to it.

**Comment by ljacomet** [comment]
I have sent a confirmation request at the email address linked to https://plugins.gradle.org/u/Kostyantyn

I also sent earlier an email about rejecting new plugin submissions, please reply there as to what should be the upcoming plugin coordinates.

**Comment by ljacomet** [comment]
Plugins are now owned by [`AndroidDev`](https://plugins.gradle.org/u/AndroidDev)
