### ISSUE TITLE
Remove plugin 1.4 version request

### ISSUE THREAD

**Issue by rnc** [gradle/plugin-portal-requests#13]
### Plugin Id
https://plugins.gradle.org/plugin/org.jboss.gm.analyzer and version 1.4

### Current Plugin Owner
I am ( under 'rnc' at Gradle Plugin repo).

### Context

I upload 

https://plugins.gradle.org/plugin/org.jboss.gm.analyzer
https://plugins.gradle.org/plugin/org.jboss.gm.manipulation

(which are from https://github.com/project-ncl/gradle-manipulator )

Unfortunately analyzer had a bad 1.4 release pushed to it by mistake. Would it be possible to delete the 1.4 please?

**Comment by lacasseio** [comment]
I see you have a version superseding that version 1.4. It's ok to have unsupported plugin versions. The better alternative would be a feature request regarding ways to mark the plugin as unsupported.

**Comment by big-guy** [comment]
To piggyback on what Daniel said.  You can delete plugin versions up to 7 days after they're published. https://plugins.gradle.org/docs/deleting

We usually want to limit delete requests to something very bad like
- Account compromises
- Malicious plugin versions
- Inappropriate uploads (e.g., license violations or proprietary code)

**Comment by rnc** [comment]
Ok thanks for the information. I hadn't realised that had published (or I would have deleted it). And yes, we have worked around it by publishing a 1.5. I think it would be very useful if there was a proper staging system like Sonatype has for Maven.

**Comment by lacasseio** [comment]
That's a great idea, please open a feature request for this.

**Comment by rnc** [comment]
@lacasseio Can you point me to where I should do that please? (or docs on that process for me to read). Thanks!

**Comment by lacasseio** [comment]
No problem, see https://plugins.gradle.org/docs/deleting
