### ISSUE TITLE
Transfer Ministry of Justice HMPPS Gradle Spring Boot plugin

### ISSUE THREAD

**Issue by petergphillips** [gradle/plugin-portal-requests#130]
### Plugin Id
uk.gov.justice.hmpps.gradle-spring-boot

### Current Plugin Owner
dps / Peter Phillips / peter.phillips@digital.justice.gov.uk

### Expected Plugin Owner
SimonMitchell / Simon Mitchell / simon.mitchell@digital.justice.gov.uk

### Context
Would like to transfer ownership of the plugin as I am moving off the team / project.  Simon has contributed to the plugin already, for example by looking at recent pull requests - https://github.com/ministryofjustice/dps-gradle-spring-boot/pulls?q=is%3Apr+is%3Aclosed

**Comment by ljacomet** [comment]
This is done https://plugins.gradle.org/plugin/uk.gov.justice.hmpps.gradle-spring-boot
