### ISSUE TITLE
Please transfer ownership of my personal plugins to my employers account

### ISSUE THREAD

**Issue by lstreepy** [gradle/plugin-portal-requests#133]
### Plugin Id

gov.raptor.gradle.plugins.binary-compatibility
gov.raptor.gradle.plugins.build-support
gov.raptor.gradle.plugins.installer-support
gov.raptor.gradle.plugins.jboss-modules

### Current Plugin Owner

larry.streepy@raptorx.org

### Expected Plugin Owner

ctic

### Context

Not sure what context you're looking for.  CTI is my employer, and we want to transfer the management of the 4 plugins listed above to CTI, so it is accessible by additional employees.

**Comment by hegyibalint** [comment]
Plugins transferred to the new user.
