### ISSUE TITLE
Plugin au.com.helixta.adl

### ISSUE THREAD

**Issue by causalnet** [gradle/plugin-portal-requests#134]
I am the original author of the ADL Gradle plugin with ID 'au.net.causal.adl' (https://plugins.gradle.org/plugin/au.net.causal.adl).  Development of this plugin is now being done by Helix who are taking over development.  

From this point on, we'd like the plugin to assume a new ID of 'au.com.helixta.adl' which reflects the company developing it.  Helix has attempted to release version 1.0.0 of the plugin but this got rejected because it was identical to the causal.net one - which it is at this point but more development is taking place).

### Plugin Id
au.net.causal.adl
(moving to au.com.helixta.adl)

### Current Plugin Owner
causalnet / prunge@causal.net.au

### Expected Plugin Owner
helix / dev-logins@helixta.com.au

### Context
Looking to allow the release of new versions of the plugin with ID 'au.com.helixta.adl'.  
Not looking to change anything with the two existing releases of the ADL plugin, just allow new releases with the new ID.

**Comment by hegyibalint** [comment]
Hi @causalnet ,

Thanks for clearing up the situation!
Just to summarize, so we are on the same page:
- The current `au.net.causal.adl` is deprecated, and the `au.com.helixta.adl` picks up the work.
  - No further action is required from our side
  - _This is a suggestion, but consider marking the deprecation in the description, so people are not lost, if they find the current one_

I see no problems from our side.

If this is all right for you, please resubmit the `au.com.helixta.adl` plugin (I will ping Helix, so if it's out of your hand, no problems), and we will continue with our regular review process!

Thanks!
