### ISSUE TITLE
The group ID is not owned by your user

### ISSUE THREAD

**Issue by stevespringett** [gradle/plugin-portal-requests#135]
Hello,

I’m the owner of [Gradle - Plugin: org.cyclonedx.bom](https://plugins.gradle.org/plugin/org.cyclonedx.bom) and recently I made a mistake and set the groupid to com.cyclonedx instead of org.cyclonedx. I’ve corrected and I’m trying to publish an updated version, but I’m receiving a message saying “The group ID org.cyclonedx is not owned by your user.”

Is it possible to remove the artifacts in com.cyclonedx and fix the permission issue so I can publish as org.cyclonedx again?

### Plugin Id
org.cyclonedx.bom

### Current Plugin Owner
stevespringett

### Expected Plugin Owner
stevespringett

**Comment by hegyibalint** [comment]
Hi @stevespringett,

One interesting thing I see is that since the first version of the plugin `com.cyclonedx` is used as group-id.
You mentioned that you used the `org` TLD, but I see no trace of this - can you explain when, because it's possible that we lost the trace of it.

Apart from this, we do not have a problem with you pushing as `com`, especially as the .org and .com point at the same location.

**Comment by ljacomet** [comment]
Actually, after double checking `org.cyclonedx` Maven group Id is owned by https://plugins.gradle.org/u/llamahunter

**Comment by stevespringett** [comment]
Oh, that is interesting.

I checked previous versions and confirmed that the groupid is `com.cyclonedx` but the name of the plugin is `org.cyclonedx`. This looks to be an oversight not affecting just the current release, but all releases. OWASP owns the .org, .com, and other domains associated with CycloneDX.

@llamahunter is actively involved in our community. 

How can we correct this going forward. I'd like to have everything published under `org.cyclonedx` as that is what our main website URL is.

**Comment by ljacomet** [comment]
Two options:
* You want to move these to a technical account for OWASP: Create it and we can transfer ownership
* You want to keep using your account, we can hand over `org.cyclonedx` immediately as there is no plugin owned by that user anyway.

**Comment by stevespringett** [comment]
We have a `cdx-automation` account on GitHub that we use with Actions to automate the release of various libraries. Gradle is currently being manually done, by my account, so this would be a good time to change that. If you could grant `cdx-automation` ownership, that would be ideal. I just went ahead and did the OAuth authorization bit.

**Comment by llamahunter** [comment]
Oops. It’s possible that when I was originally setting up the gradle plugin for cyclonedx, I used the wrong domain.

**Comment by ljacomet** [comment]
This is now done - plugin ID and both `org.cyclonedx` and `com.cyclonedx` are owned by `cdx-automation`.
