### ISSUE TITLE
Remove pending io.github.nanodeath.typedconfig submission

### ISSUE THREAD

**Issue by nanodeath** [gradle/plugin-portal-requests#136]
### Plugin Id

io.github.nanodeath.typedconfig

### Current Plugin Owner

Me.

### Context

Short version: changing plugin to a new id.

Long version: On the MavenCentral side, I have the `com.github.nanodeath` group id, but couldn't get that on the Gradle Plugin Portal side, so it's `io.github.nanodeath` there. This is confusing and I think I'd just rather move entirely onto my own domain instead, which I'll submit as a new plugin in a bit.

**Comment by abstratt** [comment]
Original submission has been deleted
