### ISSUE TITLE
Approve pending codes.draeger.jumpstart plugin

### ISSUE THREAD

**Issue by christian-draeger** [gradle/plugin-portal-requests#137]
### Plugin Id
codes.draeger.jumpstart

### Current Plugin Owner
Me (christian-draeger)

### Context

according to the mail by Balint Hegyi:
>Hi,
>
>I received your plugin submission for "codes.draeger.jumpstart.plugin".
>
>Your plugin was flagged for manual review because of the following issue(s):
>
>Plugin ID prefix 'codes.draeger.jumpstart' does not match the GitHub username 'christian-draeger'. Pls. prove ownership of the "draeger.codes" domain by adding a TXT record with value "gradle-verification=GDGWSCVAAS5YSITEKDEEJZ6Q6FZYA" to your DNS, or use a plugin ID, which ties to your GitHub user id, for example "io.github.christian-draeger.plugin"
>Please resubmit your plugin once you have corrected these issues to be reconsidered for approval. Your plugin submission has been canceled, so you may reuse the same version number.
>
>Thanks!

I published the plugin again under the following plugin ID: ‘codes.draeger.jumpstart’.
furthermore I addes a TXT record with your given value for my domain draeger.codes as well as for the subdomain jumpstart.draeger.codes. plus I added a redirect from http://jumpstart.draeger.codes/ to my corresponding github project https://github.com/christian-draeger/project-jumpstart .

Please approve. Thx in advance

**Comment by christian-draeger** [comment]
changed from removel to "waiting for approval" since it has been re-published now

**Comment by ljacomet** [comment]
This is done, sorry for the delay.
