### ISSUE TITLE
Publication fails and plugin cannot be published anymore

### ISSUE THREAD

**Issue by godfather1103** [gradle/plugin-portal-requests#138]
### Expected Behavior

Publication fails and plugin cannot be published anymore
### Context

```text
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docker-gradle-plugin-main:publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'io.github.godfather1103.docker-plugin', version: '1.0' exists already. It was created: 2022-03-20 15:18:56.348
```

### Steps to Reproduce 

1. publish plugin
2. delete plugin in webUI
3. republish plugin, Build failed with an exception.

**Comment by ljacomet** [comment]
Hello,

This can happen when the publication fails during file upload or before confirming all files are uploaded.
I see that you pushed version 1.1 since then.
Version 1.0 has been purged, you can publish it again if required.

**Comment by godfather1103** [comment]
OK
