### ISSUE TITLE
remove plugin io.github.guai.gr8s Version: 2.0

### ISSUE THREAD

**Issue by guai** [gradle/plugin-portal-requests#139]
Hi

### Plugin Id
Group: io.github.guai
Plugin id: io.github.guai.gr8s
Version: 2.0

### Current Plugin Owner
me. my github account is linked with the one on the portal

### Context
I've published a version 2.0 of my plugin, but for some reason I cannot see it here https://plugins.gradle.org/plugin/io.github.guai.gr8s
I see only version 1.2
Actually, I'd like to delete it, but cannot do it myself, since I cannot see it. Pls remove it. I plan to publish slightly enhanced version in the future and hope it will appear on the portal.

**Comment by jbartok** [comment]
Looks like the publishing process of the 2.0 version of your plugin was incomplete, that's why you don't see it. Looking into removing the remnants so that you can publish it again.

**Comment by jbartok** [comment]
You should be able to re-publish version `2.0` now, pls. check.

**Comment by guai** [comment]
thanks
