### ISSUE TITLE
Transfer ownership of plugin 'com.gemnasium.gradle-plugin' to user 'ifrenkel'

### ISSUE THREAD

**Issue by StFS** [gradle/plugin-portal-requests#14]
### Plugin Id
com.gemnasium.gradle-plugin

### Current Plugin Owner
StFS

### Expected Plugin Owner
ifrenkel

### Context
I created a Gradle plugin to generate a dependency report that could be used by Gemnasium for a dependency security scan. This is used in GitLab and my intention was to help things along by creating the initial version of the plugin. Now, the guys at GitLab are ready to receive ownership of the code and the publishing mechanism. The user 'ifrenkel' will be the one handling this on their behalf.

Here is a link to the issue keeping track of this in GitLab:
https://gitlab.com/gitlab-org/gitlab/issues/13075

**Comment by lacasseio** [comment]
Done.
