### ISSUE TITLE
Please delete plugin "eu.mihosoft.vmf:2.7.19" (only the specified version)

### ISSUE THREAD

**Issue by miho** [gradle/plugin-portal-requests#141]
Please delete plugin "eu.mihosoft.vmf:2.7.19"

### Plugin Id
id "eu.mihosoft.vmf" version "2.7.19"

### Current Plugin Owner
miho

### Context
This plugin was published by accident a long time ago. The newest version currently starts with **0.2.x**. The version published in error was missing the leading **0**.

Sorry and thanks for deleting it.

**Comment by abstratt** [comment]
No problem. Deleted.
