### ISSUE TITLE
What description is sufficient?

### ISSUE THREAD

**Issue by raintean** [gradle/plugin-portal-requests#142]
After change my plugin descption three times

---
My plugin (me.danwi.sqlex) been rejected by this issue: 
" The description of the plugin submitted is inadequate ..... "

I try to find some description example of approved plugin. such as "io.quarkus.extension", it's description just one line "Builds a Quarkus extension". same as my plugin description.

so, please tell me, how to descript my plugin?

**Comment by jvandort** [comment]
Here are a few examples of plugins with good documentation: 
https://github.com/bancolombia/scaffold-clean-architecture
https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins-source-formatter
https://github.com/him188/kotlin-jvm-blocking-bridge
https://github.com/IntershopCommunicationsAG/icm-docker-plugin

Hopefully these can serve as a guide to the kind of information you should include with your plugin's documentation.

**Comment by raintean** [comment]
Can it's document page just use chinese?
