### ISSUE TITLE
Remove: https://plugins.gradle.org/plugin/de.jjohannes.gradle.java-ecosystem-capabilities (Version 0.1)

### ISSUE THREAD

**Issue by jjohannes** [gradle/plugin-portal-requests#143]
### Plugin Id

`de.jjohannes.gradle.java-ecosystem-capabilities` (just one Version - `0.1`)
### Current Plugin Owner

Me.

### Context

I accidentally published using the wrong plugin ID. The correct one is `de.jjohannes.java-ecosystem-capabilities` (without the `gradle` segment).

**Comment by ljacomet** [comment]
Hey Jendrik 👋 

And you never advertised that wrong plugin ID, right?

Just checking as we try to not break builds.

**Comment by jjohannes** [comment]
Hi Louis,

Thanks for taking care of this! I actually promote the new/right ID. And the first (rather experimental; v0.1) plugin was just published some weeks ago. Otherwise I wouldn't ask. I just noticed my mistake a little bit too late to press delete myself. :)

My main concern is that it is confusing to have two Plugins with quite similar IDs turn up if you use the plugin portal search.
