### ISSUE TITLE
Transfer com.bugsnag.android.gradle to bugsnag

### ISSUE THREAD

**Issue by loopj** [gradle/plugin-portal-requests#144]
### Plugin Id
com.bugsnag.android.gradle

### Current Plugin Owner
loopj

### Expected Plugin Owner
bugsnag

### Context
I'm not longer with the company

**Comment by tomlongridge** [comment]
Just to confirm, we are ready to take ownership under the above account. Please let me know if there are any queries.

**Comment by abstratt** [comment]
Change made
