### ISSUE TITLE
Login to Forums via Github leads to transient error

### ISSUE THREAD

**Issue by abstratt** [gradle/plugin-portal-requests#147]
This is being reported against Plugin Portal because the Forum authentication happens via plugins.gradle.org.

Authentication to discuss.gradle.org happens via this page:

https://plugins.gradle.org/user/login?redirectUrl=...

### Expected Behavior

Login to discuss.gradle.org using Github credentials should work fine.

### Current Behavior

Login to discuss.gradle.org using Github credentials fails after user successfully authenticates with Github. 

The user receives an error message like this:

>  Bad Request
> An client error (id is: "688568") has been logged
> 
> Send us a [mail](mailto:plugin-portal-support@gradle.com) if this is our fault

### Steps to Reproduce 

1. ensure you are not logged in to discuss.gradle.org or plugins.gradle.org. I use an anonymous window for this
2. go to discuss.gradle.org
3. hit the Login button
4. you should be redirected to the login page, with a URL looking like: https://plugins.gradle.org/user/login?redirectUrl=...
5. choose to login via GitHub instead of providing username and password
6. log in via Github
7. after authentication successfully completes, you should get the error message described above

Note that if you go to discuss.gradle.org and try to hit the login button again, it will finally show you as logged in.

### Your Environment

Chrome version 102.0.5005.61 (Official Build) (arm64)
MacOSX

**Comment by gotson** [comment]
I can't login by following the steps above. Any ETA on fixing this?

**Comment by ljacomet** [comment]
A fix is being worked on.

**Comment by ljacomet** [comment]
The fix is now deployed and login on the forums while using GitHub works properly now.
