### ISSUE TITLE
Remove plugin com.github.rodm.teamcity-agent version 1.5-beta-1

### ISSUE THREAD

**Issue by rodm** [gradle/plugin-portal-requests#148]
### Plugin Id
com.github.rodm.teamcity-agent version 1.5-beta-1

### Current Plugin Owner

rodm

### Context
Tried to publish the above plugin along with 4 other plugins in the project, one of the plugins is
new but had an id prefix of 'com.github' causing the publish to fail after the above plugin.

**Comment by ov7a** [comment]
Hi! Sorry for the late reply. This repository was out of our team's attention for a while. 

I'm closing this issue as stale. 

Note that our policy is to remove old plugin versions only if there is a security issue.
