### ISSUE TITLE
plugin-publish: Plugin published but not activated

### ISSUE THREAD

**Issue by osipxd** [gradle/plugin-portal-requests#149]
I've published a plugin using `publishPlugins` task, but for some reason activation failed and the plugin stuck in the state when it is uploaded but not activated.

```md
> Task :infrastructure-publish:publishPlugins FAILED
Publishing plugin com.redmadrobot.publish version 0.16.2
Publishing plugin com.redmadrobot.publish-config version 0.16.2

Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':infrastructure-publish:publishPlugins'.
> Unauthorized!
    Login from command line using:
      gradle login
    or login and download user API keys on:
      https://plugins.gradle.org/user/login
```

After this error, I've restarted `publishPlugins` (without login) and "Unauthorized" error just gone. But now I get another error:

```
Execution failed for task ':infrastructure-publish:publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'com.redmadrobot.publish', version: '0.16.2' exists already. It was created: 2022-06-17 09:52:13.076
```

### Expected Behavior

There is possibility to activate or delete uploaded version, via website, for example.

### Current Behavior

I can't publish version again (it is already uploaded) as well as I can't delete the uploaded version because it is not activated.

### Your Environment

[com.gradle.plugin-publish:0.21.0](https://plugins.gradle.org/plugin/com.gradle.plugin-publish/0.21.0)

**Comment by donat** [comment]
The plugin is published now

**Comment by donat** [comment]
FYI the preferred way to reach out to Gradle is by opening an issue on this repository or via the following link: https://plugins.gradle.org/docs/get-help.

**Comment by osipxd** [comment]
Yes, the plugin is published using workaround I've mentioned before. But it wasn't the point of the issue.
The point is to prevent such situations further.

Possible solutions I see:
- Add possibility to activate and/or delete not activated versions (via website, via gradle task, etc.)
- Activate version automatically if it is already exist but not activated and developer executed `publishPlugins` task again
- Show message like "Write us https://plugins.gradle.org/docs/get-help and we'll activate your plugin" if plugin stuck in invalid state
