### ISSUE TITLE
A Deleted Plugin Can Still Be Successfully Applied In A Project

### ISSUE THREAD

**Issue by lingocoder** [gradle/plugin-portal-requests#15]
A plugin that I deleted from the plugin portal several days ago, is still reachable over the  external  network.

### Expected Behavior

When I delete a plugin from the portal, I expect that it would not be possible to apply that version of the plugin in a project and have the *deleted* version successfully resolved over the internet.

### Current Behavior

While one user reported that his attempted usage of the deleted plugin failed to be found in the portal, my own usage of the plugin was successfully downloaded from the portal somehow.

### Context

I deleted [*com.lingocoder.mrjar 0.0.16*](http://bit.ly/mrJar) about four days ago. Two days ago, @jdneo, maintainer of [*the vscode-java-test project confirmed*](https://github.com/microsoft/vscode-java-test/issues/872#issuecomment-554286809) that — *at least for him* — that particular version of ***mrJar*** was indeed not available from the plugin portal.

Today, four days after I deleted it, a project in which I'd applied that version appears to be able to reach the *deleted* version over the internet somehow.

### Steps to Reproduce 

1. Login to the plugin portal
2. Delete a version of the plugin that was published within the last seven days
3. Four days later, apply the deleted version of the plugin in a project
4. Observe that the plugin was apparently not actually deleted...

![deleted but reachable 0 d](https://user-images.githubusercontent.com/49788472/69003847-c8dd2a00-08bd-11ea-89dc-00d1780470d9.gif)

...You can see in the recording that the build scan reports the access to the plugin as being *apparently* through the portal (*`External`*). You can also see in the recording, that I've checked the *`settings.gradle`* of the project(*s*) in question. I believe that I have clearly confirmed that the projects are not configured to use a local publication of the plugin. I presume that is what *`External`* means in the build scan.

### Your Environment

Gradle 6.0-rc-2
OpenJDK 12
Windows amd64
com.lingocoder.mrjar 0.0.16

**Comment by lacasseio** [comment]
Thanks @lingocoder, [your build scan does indeed show the plugin being resolved](https://scans.gradle.com/s/gfq5vu5y46rhc/build-dependencies?dependencies=mrjar&expandAll&focusedDependency=WzEsMCwzNSxbMCwwLFswXV1d&focusedDependencyView=details), however what the build scan won't show you is if the plugin is already cached on your machine. I tried reproducing but [saw the same thing as the other user](https://scans.gradle.com/s/i7jbb47zrlb7y). I'm led to believe the plugin is simply cached on your machine and Gradle simply resolve it from there. You good your build again with `--gradle-user-home`. The build should fail due to nothing cached in this new user home.

**Comment by lingocoder** [comment]
Thanks @lacasseio ,

I understand most of your explanation. That's pretty much along the lines of what I suspected. But I couldn't work out what this means:

> „...*You good your build again with --gradle-user-home*...“

That's probably a typo. No?

**Comment by lacasseio** [comment]
Right, sorry about that. It was really late for me. What I mean is you could confirm this suspicion by running the passing build again using a clean user home via `--gradle-user-home` or the environment variable. This would effectively force Gradle to redownload the plugin and should fail as expected.
