### ISSUE TITLE
Transfer org.mozilla.apilint to /u/jonathan

### ISSUE THREAD

**Issue by agi90** [gradle/plugin-portal-requests#151]
### Plugin Id:
org.mozilla.apilint

### Current Plugin Owner
/u/agi90

### Expected Plugin Owner
/u/jonathan

### Context
I'm leaving Mozilla so I won't be maintaining the plugin anymore, my coworker @jonalmeida kindly offered to take over.

**Comment by eskatos** [comment]
Hi,

The current owner of this plugin is linked to a different GitHub account than `agi90`.

Please use the GitHub account currently linked to the owner of the plugin to request an ownership transfer or send us a confirmation email from the address linked in the current owner portal profile to plugin-portal-support@gradle.com.

In absence of confirmation this issue will be closed by the end of the week.

**Comment by agi** [comment]
Is this the right account? I can confirm the request to transfer the plugin ownership.
