### ISSUE TITLE
Drop 2.1.0-eap-1 version from io.ktor.plugin

### ISSUE THREAD

**Issue by e5l** [gradle/plugin-portal-requests#152]
Please help us drop the `2.1.0-eap-1` version of the Ktor plugin.

Drop `2.1.0-eap-1` version.

### Current Plugin Owner
https://plugins.gradle.org/u/Ktor

### Context
We have a problem that stable versions will no longer be displayed as the latest because of `eap` suffix in this build. So we will move `eap` builds to a different repo.

**Comment by eskatos** [comment]
Done
