### ISSUE TITLE
Transfer com.liftric.octopus-deploy-plugin and com.liftric.vault-client-plugin

### ISSUE THREAD

**Issue by Ingwersaft** [gradle/plugin-portal-requests#153]
Please move the following two plugins from my personal account to the proper company account. 
 
### Plugin Id
`com.liftric.octopus-deploy-plugin`
and
`com.liftric.vault-client-plugin`

### Current Plugin Owner
https://plugins.gradle.org/u/Ingwersaft

### Expected Plugin Owner
https://plugins.gradle.org/u/liftric

### Context
Now that we at [Liftric](https://github.com/Liftric/) have a third plugin in the works we want to move the previous plugins to the company account. Also I think we can't add new plugins with the `com.liftric` namespace because it is taken by my account.

Thanks in advance!

**Comment by eskatos** [comment]
Ownership of the two plugins has been transferred
