### ISSUE TITLE
Tansfert com.ekino.oss.plugin.kotlin-quality to ekino

### ISSUE THREAD

**Issue by philippeagra** [gradle/plugin-portal-requests#156]
### Plugin Id

com.ekino.oss.plugin.kotlin-quality

### Current Plugin Owner

pagra

### Expected Plugin Owner

ekino

### Context

Plugin wrongly published with a personal account. The plugin package uses the ekino package (com.ekino.oss.plugin). Others plugins are already uploaded with the ekino account (docker, java, quality).

**Comment by donat** [comment]
Fixed
