### ISSUE TITLE
Transfer ownership of eu.xenit.* plugins

### ISSUE THREAD

**Issue by vierbergenlars** [gradle/plugin-portal-requests#159]
### Plugin Id

All plugins with a plugin id starting with `eu.xenit` in my personal account https://plugins.gradle.org/u/vierbergenlars

### Current Plugin Owner

https://plugins.gradle.org/u/vierbergenlars

### Expected Plugin Owner

https://plugins.gradle.org/u/xenit

### Context

I would like to transfer ownership of the Gradle plugins for my company from my personal account to a shared company account.

**Comment by todorinskiz** [comment]
@ljacomet @big-guy @lacasseio Who can we contact to help us out with the ownership transfer?

**Comment by lacasseio** [comment]
I don't work at Gradle anymore. However, waiting 6 months for a ownership transfer is quite absurd. I would escalate it to @pioterj so they can review their process for addressing plugin portal requests like this one.

**Comment by ljacomet** [comment]
Hey,

Sorry, this fell through the cracks and should have been handled sooner. Making sure this get handled today.

**Comment by FrauBoes** [comment]
I completed the transfer, if there's any issue, let me know!

**Comment by todorinskiz** [comment]
Thank you all for the quick reaction!
