### ISSUE TITLE
Resend activation email

### ISSUE THREAD

**Issue by krystian-panek-wttech** [gradle/plugin-portal-requests#161]
may I ask for resending activation e-mail for account registered with [gradle-plugins@wundermanthompson.com](mailto:gradle-plugins@wundermanthompson.com) on https://plugins.gradle.org/? I believe I signed up too early and e-mail didn't come (I just registered it) . I also attempted with resetting password but still I cannot observe any e-mail in my company's mailbox; I already tested that mailbox by sending some test message from my private account and it works fine; any help appreciated :wink:

I cannot signup again as both username and e-mail are already taken. Seems that there is no resend activation link feature so I got stuck. Please help ;)

**Comment by donat** [comment]
I don't see any users with the email `gradle-plugins@wundermanthompson.com`. Do you know the username maybe? Also, you might be able to try again with the registration.

**Comment by krystian-panek-wttech** [comment]
wttech

**Comment by krystian-panek-wttech** [comment]
@donat Rly? Sign up page has different opinion 😂

![Screenshot_2022-10-05-20-20-16-614_com android chrome](https://user-images.githubusercontent.com/81212505/194133616-add83a99-2073-4f89-9b14-f6cf2478d270.jpg)

**Comment by donat** [comment]
I've created a new user with the requested username/password. Please try resetting the password and logging in.

**Comment by jbartok** [comment]
@pun-ky in my attempt to pick up where you guys left off and help you, I've missed the later part of the thread and have deleted this user entirely... Pls. try to re-create it and let's see if it will work this time.

**Comment by krystian-panek-wttech** [comment]
> have deleted this user entirely

I don't think so @jbartok 

![image](https://user-images.githubusercontent.com/10673561/194855911-116badb0-de5f-49df-8b6f-1c2c7b452dc9.png)

**Comment by jbartok** [comment]
Investigating.

**Comment by jbartok** [comment]
Pls. try now. I think the outstanding activation token was what kept the username blocked. I've deleted it now.

**Comment by krystian-panek-wttech** [comment]
yep, it helped. now works finally; thx @jbartok
