### ISSUE TITLE
Remove Plugin "com.dailystudio.devbricksx.devkit"

### ISSUE THREAD

**Issue by dailystudio** [gradle/plugin-portal-requests#162]
### Plugin Id
com.dailystudio.devbricksx.devkit (version: 0.5.0)

### Current Plugin Owner
dailystudio

### Context
I am a newbie to developing a Gradle plug-in. I just tested the publication of my plugin to the Gradle Plugin portal. But it seems that it has the wrong groupId and plugin Id. GroupId should be "cn.daillystudio" not "com.dailystudio.devbricksx", while the plugin Id should be "cn.dailystudio.devbricksx.devkit" not "com.dailystudio.devbricksx.devkit"
It is still in "Pending Approval" status, but I can't find any way to delete it from my side. So, I am wondering if it is possible to remove it and I will upload the correct one later. Or could you just help me change its groupdId and pluginId?

**Comment by dailystudio** [comment]
I am also a bit confused, since I just test publishing it in local maven repo. In my mind, if the groupId and pluginId is correct, I could refer to it with the following name:
classpath "cn.dailystudio:cn.dailystudio.devbricksx.devkit:0.5.0"
It is composed with the rule "groupdId:pluginId:version"

But, now, I need to refer to:
classpath "cn.dailystudio.devbricksx.devkit:cn.dailystudio.devbricksx.devkit.gradle.plugin:0.5.0"
It seems to follow the naming rule "pluginId: pluginId.gradle.plugin:version". Is there a naming rules I missed.

**Comment by 6hundreds** [comment]
Hi @dailystudio 
The reason why you need to refer to plugin in such way is described here https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

Also, you plugin submission was rejected, you can do needed adjustments and submit it again
