### ISSUE TITLE
Transfer ownership of the io.wttech.habit plugin from habitwttech to the wttech account.

### ISSUE THREAD

**Issue by tomasz-krug-wttech** [gradle/plugin-portal-requests#163]
### Plugin Id
io.wttech.habit

### Current Plugin Owner
habitwttech

### Expected Plugin Owner
wttech

### Context
Habit was the first plugin to be published on the Gradle Plugin Portal with the io.wttech prefix. For this I have created a new account on the Plugin Portal (habitwttech).
When a new plugin was to be submitted (io.wttech.config) it was mentioned in the submission email thread the plugins should be moved to one of accounts so the whole namespace (io.wttech) is managed centrally.

io.wttech.habit should be transfered to the central account (wttech) where io.wttech.config is already managed.

Both Gradle Plugin accounts are registered using email addresses from the @wundermanthompson.com domain.

**Comment by 6hundreds** [comment]
@tomasz-krug-wttech Ownership was transfered
