### ISSUE TITLE
Outdated .meta/prefix.txt file in Gradle plugins maven repository

### ISSUE THREAD

**Issue by oskrkal** [gradle/plugin-portal-requests#164]
There is an outdated prefix file at https://plugins.gradle.org/m2/.meta/prefixes.txt. This file should contain a list of all valid path prefixes of artifacts present in the repository.

### Expected Behavior
The file https://plugins.gradle.org/m2/.meta/prefixes.txt should be up-to-date and list **all** top-level or second-level directories present in the repository https://plugins.gradle.org/m2/, or it should be missing (HTTP 404).

### Current Behavior
The file currently does not contain all top-level directories. For example, any prefixes for the */nebula* tree are missing in the file, while the tree actually exists at https://plugins.gradle.org/m2/nebula/, and thus, the tree is completely hidden from repository managers processing the prefix file.

### Context
If a repository contains .meta/prefix.txt file, it can be used by some repository managers (for example Sonatype Nexus Repository Manager) to quickly decide whether a specific artifact can be present in the repository or not. If the repository manager receives a request for a file and does not find the beginning of its path in the list, it automatically reports this file as unavailable in the local mirror, without querying the remote repository.

We use Sonatype Nexus Repository Manager to mirror external repositories and our engineers are obliged to use the internal mirror instead of downloading artifacts directly from the Internet. Today, one of the engineers reported that he is not able to download plugin /nebula/ospackage-base/nebula.ospackage-base.gradle.plugin/8.3.0/nebula.ospackage-base.gradle.plugin-8.3.0.pom, although it is available in the public Gradle plugin Maven repository on the Internet. Further investigation revealed that this was caused by an outdated .meta/prefix.txt file present in the repository that was more than 500 days old.

### Steps to Reproduce 
`curl -sL https://plugins.gradle.org/m2/.meta/prefixes.txt | grep '^/nebula'`

This should either return non-empty output, or the request for the file should end with 404 Not Found response.

### Your Environment
Sonatype Nexus Repository Manager 2.15.1-02

**Comment by oskrkal** [comment]
Related topic in Gradle Forums: https://discuss.gradle.org/t/possibly-corrupted-prefixes-txt-on-plugin-portal/44080

**Comment by ov7a** [comment]
This is fixed and 404 is returned for that url:
```
curl -i https://plugins.gradle.org/m2/.meta/prefixes.txt       
     
HTTP/1.1 404 Not Found
```
