### ISSUE TITLE
Prefer maven central over jcenter for fallback resolution

### ISSUE THREAD

**Issue by ben-manes** [gradle/plugin-portal-requests#165]
JCenter has historically had poor stability and, given its shutdown, has grown worse in that regard. As the plugin repository will proxy for non-plugin dependencies, it might help to prefer redirecting to Central before JCenter if possible. The Gradle build lists Central prior to the plugin portal to try and give an ordering preference.

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve javax.xml.bind:jaxb-api:2.3.0.
     Required by:
         project :
      > Could not resolve javax.xml.bind:jaxb-api:2.3.0.
         > Could not get resource 'https://plugins.gradle.org/m2/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.pom'.
               > Remote host terminated the handshake
```

Unfortunately plugins hosted on the portal can also fail, even though previously it has been stated that these are not hosted by JCenter.
```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve me.champeau.jmh:jmh-gradle-plugin:0.6.8.
     Required by:
         project :
      > Could not resolve me.champeau.jmh:jmh-gradle-plugin:0.6.8.
         > Could not get resource 'https://plugins.gradle.org/m2/me/champeau/jmh/jmh-gradle-plugin/0.6.8/jmh-gradle-plugin-0.6.8.module'.
            > Could not GET 'https://jcenter.bintray.com/me/champeau/jmh/jmh-gradle-plugin/0.6.8/jmh-gradle-plugin-0.6.8.module'.
               > Remote host terminated the handshake
```

<img width="1792" alt="Screen Shot 2022-10-20 at 9 58 44 AM" src="https://user-images.githubusercontent.com/378614/197012049-7091acc8-f60a-4816-b489-497723bdc6b0.png">

**Comment by ben-manes** [comment]
It is an unfortunate situation. A lot of basic automation for site reliability is lacking that causes outages, which they have no further reasons to be interested in improving. For example, today they let their SSL certificate expire and given their track record it will be many hours or days before they bother to fix this.

<img width="1792" alt="Screen Shot 2022-11-25 at 5 17 37 PM" src="https://user-images.githubusercontent.com/378614/204067125-b65af77b-2fc1-4f3a-8828-ac4b447104ae.png">

**Comment by ov7a** [comment]
We changed the redirect on July 15th.

See our [blog post](https://blog.gradle.org/portal-jcenter-impact) for more details.
