### ISSUE TITLE
Update description and tags on sonarlint plugin

### ISSUE THREAD

**Issue by Lucas3oo** [gradle/plugin-portal-requests#169]
Hi

Can you please update the sonarlint plugin with this description and tags:

"SonarLint static code analysis using stand-alone SonarLint engine, for Java, Kotlin and Node projects. Min Gradle version 7.0."
      'sonarlint',
      'java',
      'kotlin',
      'node',
      'code quality',
      'lint',
      'static code analysis',
      'static analysis',
      'code analysis',
      'codesmells'

The link to the plugin:
https://plugins.gradle.org/plugin/se.solrike.sonarlint
Github: https://github.com/Lucas3oo/sonarlint-gradle-plugin

Thanks
Lucas

**Comment by ljacomet** [comment]
This has been done

**Comment by Lucas3oo** [comment]
Tx!
/Lucas
