### ISSUE TITLE
Two different descriptions are displayed — And old one and a recently updated one

### ISSUE THREAD

**Issue by lingocoder** [gradle/plugin-portal-requests#17]
The com.lingocoder.mr v0.0.16 plugin displays two different descriptions. One is correct and should be displayed wherever a description is needed:

* „*Adds easy JPMS module creation capabilities to Gradle. Enhances Buildship/Eclipse with JPMS modularity. Easy Multi-Release JAR File assembly*“

----

![issue17 0 b](https://user-images.githubusercontent.com/49788472/69601122-1e76ac80-100b-11ea-812a-6d649d37aa5d.png)
 
----

The other one is outdated and should have been replaced by the more recently-published one above:

* „*A Gradle plugin that supports compiling, testing, assembling and maintaining Multi-Release JAR Files*“

----

![issue17 0 a](https://user-images.githubusercontent.com/49788472/69601121-1dde1600-100b-11ea-99bb-565342b93ff4.png)

----

### Expected Behavior

I expected that the description that I specified in the build script that published the plugin to be displayed wherever the portal displays descriptions

### Current Behavior

On the main portal landing page and on search result pages, the portal displays an old outdated description.

### Context

I would like people who come upon my plugin in search results to see the correct, more currently-appropriate description of the plugin.

### Steps to Reproduce 

1. Visit [*the portal landing page*](https://plugins.gradle.org/)

2. In the search box, enter „*jpms*“
   * com.lingocoder.mrjar appears in the results.

3. Observe that the description displays the above outdated text.

4. Click on the com.lingocoder.mrjar search result link.

5. Observe that on the plugin's page, a different description (*the correct one*) is displayed.

### Your Environment

Not applicable.

**Comment by lacasseio** [comment]
Thanks for reporting this issue, it's actually not a bug, but definitely surprising. The "description" you are setting during publication is the _sort-of_ release note of your plugin which is displayed by version. For changing the main plugin description, it needs manual intervention from our end so filing a issue here is the right thing to do. I will address this shortly, and I encourage you to open a feature request.

**Comment by lacasseio** [comment]
The description was changed. Open a feature request if you want this to be part of the Plugin Portal or at least report it as an unexpected behavior of plugin portal publication process.
