### ISSUE TITLE
Request to change ownership for `io.github.frontrider.godle`

### ISSUE THREAD

**Issue by Frontrider** [gradle/plugin-portal-requests#172]
### Plugin Id
io.github.frontrider.godle

### Current Plugin Owner
https://plugins.gradle.org/u/Ankis 

### Expected Plugin Owner
https://plugins.gradle.org/u/Frontrider

### Context
I made an account before realizing that I can log in with github, and now the plugin seems to be stuck on the one that is not linked, because I had the wrong credentials installed.

It should be on the one that is linked to github for your convenience. It was supposed to be deleted, but I guess that does not mean that I can use it freely again.

**Comment by jbartok** [comment]
The plugin had a broken/aborted publication. I've cleaned it up, pls. try
again.

József Bartók
Senior Software Engineer
Gradle
W. gradle.com

**Comment by Frontrider** [comment]
The error remains the same:

Failed to post to server.
Server responded with:
The user 'Frontrider' does not have write permissions to plugin [io.github.frontrider.godle]

**Comment by jbartok** [comment]
I've changed the plugin owner to Frontrider now, pls. try again, let me
know if it's still not working.
József Bartók
Senior Software Engineer
Gradle
W. gradle.com
