### ISSUE TITLE
Transfer `org.hidetake.ssh`

### ISSUE THREAD

**Issue by int128** [gradle/plugin-portal-requests#176]
Hi,
I cannot release a new version of this plugin because Bintray is no longer available.
https://github.com/int128/gradle-ssh-plugin/issues/378#issuecomment-1383058232

### Plugin Id
```
org.hidetake.ssh
```

https://plugins.gradle.org/plugin/org.hidetake.ssh

### Current Plugin Owner
Not associated. It was published from Bintray.

### Expected Plugin Owner
https://plugins.gradle.org/u/int128

### Context
Bintray migration. This plugin is not shown in "Reclaim" tab in the portal.

**Comment by twwwt** [comment]
Could someone please have a look on this? Thanks.

**Comment by MrZeusTheCoder** [comment]
+1

**Comment by ljacomet** [comment]
Hello,

This is now done. Sorry for the delay.

**Comment by MrZeusTheCoder** [comment]
No problem! Thank you so much for moving this along.

**Comment by int128** [comment]
Thanks a lot.
