### ISSUE TITLE
Please remove com.verificationgentleman.gradle.hdvl.* version v0.2.2

### ISSUE THREAD

**Issue by tudortimi** [gradle/plugin-portal-requests#177]
### Plugin Ids
com.verificationgentleman.gradle.hdvl.* version v0.2.2

The expanded list:
com.verificationgentleman.gradle.hdvl.systemverilog
com.verificationgentleman.gradle.hdvl.c
com.verificationgentleman.gradle.hdvl.svunit
com.verificationgentleman.gradle.hdvl.svunit-build
com.verificationgentleman.gradle.hdvl.svunit-build-injector
com.verificationgentleman.gradle.hdvl.dvt

### Current Plugin Owner
tudortimi

### Context
I have accidentally added a `v` as a version prefix. I have released another version with the name `0.2.2` (no `v`) to replace it.

**Comment by ljacomet** [comment]
You have 7 days to delete invalid publications. Please do the removal yourself.

**Comment by tudortimi** [comment]
Nice, this makes it much easier.

**Comment by tudortimi** [comment]
Also, sorry for not properly reading the README. I see now this is documented there.
