### ISSUE TITLE
Not authorised to write to org.jsonschema2pojo

### ISSUE THREAD

**Issue by joelittlejohn** [gradle/plugin-portal-requests#178]
Hi,

I run this project: [joelittlejohn/jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo). I also own this domain: https://jsonschema2pojo.org/.

My github username is joelittlejohn, and my [gradle.org](http://gradle.org/) username is the same. When I attempt to publish my plugin I see this message:

Failed to post to server.
Server responded with:
The user ‘joelittlejohn’ does not have write permissions to plugin [org.jsonschema2pojo]

Could someone ensure I am able to write to this id? I’m happy to do whatever validation steps are needed.

Thanks!!

**Comment by ljacomet** [comment]
Hello,

From looking at our system, there seems to be a broken state to be cleaned up.

Note however that [searching on the plugin portal](https://plugins.gradle.org/search?term=org.jsonschema2pojo) finds an existing plugin that seems to have a matching feature set.

Could you reach out to the author and see if it makes sense to have two different plugins?

**Comment by ljacomet** [comment]
I have cleaned up the broken state, you should be able to submit a plugin for approval.

Note that the potential duplicate question remains.
