### ISSUE TITLE
gay.pizza project plugins

### ISSUE THREAD

**Issue by azenla** [gradle/plugin-portal-requests#179]
Hello,

I received a rejection for gay.pizza.foundation.* plugins, which I have republished.
It was told in the email that gay.pizza is not a real domain, but it is in fact the real domain (https://gay.pizza is the main site but pizza.gay is an alias) for https://github.com/GayPizzaSpecifications

Gay Pizza Specifications is an LGBTQ ran GitHub organization.

Please approve these plugins in the description changes if they are satisfactory.

Thanks!

**Comment by FrauBoes** [comment]
Thanks for updating the description of the plugin and providing more information on the domain. 

Please resubmit your plugin to be reconsidered for approval. Your plugin submission has been canceled, so you may reuse the same version number.
