### ISSUE TITLE
Tansfer `com.heroku.sdk.heroku-gradle` to `heroku-languages-team`

### ISSUE THREAD

**Issue by Malax** [gradle/plugin-portal-requests#180]
### Plugin Id
com.heroku.sdk.heroku-gradle

### Current Plugin Owner
Joe Kutner (@jkutner)

### Expected Plugin Owner
heroku-languages-team (https://plugins.gradle.org/u/heroku-languages-team)

### Context
This Heroku plugin was initially released when bintray was still a thing. It was created by @jkutner who was the main person responsible for this plugin. Roles within the company have changed since then. We want to move the plugin to a non-personal account so that we don't run into this issue again in the future.

**Comment by FrauBoes** [comment]
Ownership has been transferred

**Comment by jkutner** [comment]
👍
