### ISSUE TITLE
Transfer ownership of `org.zaproxy` plugins

### ISSUE THREAD

**Issue by thc202** [gradle/plugin-portal-requests#181]
### Plugin Id
I'd like to transfer the ownership of the plugins under `org.zaproxy`:
https://plugins.gradle.org/plugin/org.zaproxy.add-on
https://plugins.gradle.org/plugin/org.zaproxy.crowdin

### Current Plugin Owner
https://plugins.gradle.org/u/thc202

### Expected Plugin Owner
https://plugins.gradle.org/u/zapbot

### Context
I'm the current owner of those plugins and I'd like to transfer them to a common account, we (@zaproxy) have been using the `zapbot` accounts for that purpose (e.g. @zapbot).

Tagging the core @zaproxy team: @psiinon, @kingthorin, and @ricekot.

**Comment by kingthorin** [comment]
Approved 😀

**Comment by FrauBoes** [comment]
Ownership has been transferred.

**Comment by thc202** [comment]
Thank you!
