### ISSUE TITLE
Update owner of `com.atlassian.performance.tools.gradle-release`

### ISSUE THREAD

**Issue by dagguh** [gradle/plugin-portal-requests#182]
### Plugin Id
`com.atlassian.performance.tools.gradle-release`
https://plugins.gradle.org/plugin/com.atlassian.performance.tools.gradle-release

### Current Plugin Owner
https://plugins.gradle.org/u/spawlak_atlassian

### Expected Plugin Owner
https://plugins.gradle.org/u/atlassian-mkwidzinski

### Context
We've got a new owner in the team.

**Comment by jbartok** [comment]
Would it be possible for you folks to set up a group account, not specific to any one developer? 
And then we could set the plugin ownership to that and never need to change it again? 
I will also need confirmation from the original owner (spawlak@atlassian.com) that he's ok with the change.

**Comment by dagguh** [comment]
Sebastian moved on quite a while back, as you can see in [the commit list](https://bitbucket.org/atlassian/gradle-release/commits/?page=2):
![image](https://user-images.githubusercontent.com/1194704/223441465-3c79e753-96f3-4913-9358-82d1d8e6ad5e.png)
We have control over the plugin already. As a proof, I can release a new version or reset API keys.

> Would it be possible for you folks to set up a group account, not specific to any one developer?
> And then we could set the plugin ownership to that and never need to change it again?

Good call. I requested a group account today, but it could take some time due to company policies, etc. BTW is it possible to designate [@atlassian/jpt team](https://github.com/orgs/atlassian/teams/jpt) as the owner?

**Comment by jbartok** [comment]
Ok, all good on our side. 
When I say "group account" I mean a Plugin Portal account, NOT a GitHub one (although we prefer Plugin Portal accounts to also be linked to GitHub accounts).
Let me know when such a Plugin Portal account is set up and then I can use that.

**Comment by dagguh** [comment]
Ok, I requested a group account in our IT. Is it possible to link a Plugin Portal account with a GitHub team (rather than GitHub account)?

**Comment by dagguh** [comment]
Here's the account: https://plugins.gradle.org/u/atlassian

**Comment by jbartok** [comment]
Ownership has been changed, please reopen the issue if you see any problems.
