### ISSUE TITLE
Request to update description and tags for plugin 'se.solrike.sonarlint'

### ISSUE THREAD

**Issue by Lucas3oo** [gradle/plugin-portal-requests#186]
Hi

Can you please update the sonarlint plugin with this description and tags:

Description:
SonarLint static code analysis using stand-alone SonarLint engine, for Java, Kotlin, Scala and Node.js projects. Min Gradle version 7.0.

Tags:
      'code analysis',
      'code quality',
      'codesmells',
      'java',
      'kotlin',
      'lint',
      'node.js',
      'sarif',
      'scala',
      'software composition analysis',
      'sonarlint',
      'spotbugs',
      'static analysis',
      'static code analysis'

--------
The link to the plugin:
https://plugins.gradle.org/plugin/se.solrike.sonarlint
Github: https://github.com/Lucas3oo/sonarlint-gradle-plugin

Thanks
Lucas

**Comment by ov7a** [comment]
Hi! Done.

**Comment by Lucas3oo** [comment]
Thanks a lot 😊
