### ISSUE TITLE
Show VCS url on the plugin page

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#19]
### Expected Behavior

Show the VCS URL configured for each published plugins. When the url is configured like the following:

<img width="602" alt="Screen Shot 2019-11-29 at 4 40 13 PM" src="https://user-images.githubusercontent.com/22181740/69869869-93760a80-12c7-11ea-82a1-956ffc98895e.png">

It should show on the plugin page.

### Current Behavior

The plugin page doesn't show the VCS URL making it harder to find the source code that was used to build the plugin:

<img width="721" alt="Screen Shot 2019-11-29 at 4 40 43 PM" src="https://user-images.githubusercontent.com/22181740/69869883-9d980900-12c7-11ea-80ea-adb5dab4e115.png">

### Context

See https://github.com/gradle-guides/gradle-guides-plugin/issues/55

**Comment by ov7a** [comment]
Fixed:

<img width="515" alt="image" src="https://github.com/gradle/plugin-portal-requests/assets/4946730/41998399-6823-4cfd-9c33-e5e4ae684fd5">
