### ISSUE TITLE
Plugin ownership transfer: `com.ibm.zosconnect.gradle` and `com.ibm.zosconnect.requester` to `zosconnect-functional-id`

### ISSUE THREAD

**Issue by ind1go** [gradle/plugin-portal-requests#192]
### Plugin Id

2 plugins:
- `com.ibm.zosconnect.gradle`
- `com.ibm.zosconnect.requester`

### Current Plugin Owner

Me - https://plugins.gradle.org/u/ind1go

### Expected Plugin Owner

https://plugins.gradle.org/u/zosconnect-functional-id

### Context

This transfer from a personal account to a shared functional ID will help us at IBM to share and automate the management of these plugins.

**Comment by eskatos** [comment]
Hi,

We'd need a confirmation from the [zosconnect-functional-id](https://plugins.gradle.org/u/zosconnect-functional-id) account email that the ownership transfer is legit.

Could you have someone send an email from the zosconnect-functional-id account email to plugin-portal-support@gradle.com confirming the ownership transfer?

Thanks

**Comment by eskatos** [comment]
Thank you for the confirmation.

Both plugins ownership has been transferred.
