### ISSUE TITLE
Received email plugin published but portal keeps saying Pending Approval

### ISSUE THREAD

**Issue by msche** [gradle/plugin-portal-requests#196]
I have released 2 versions of the plugin `io.datapith.jayOverlay` after each other (0.1.3 and 0.1.4) and for the last one I received a email that it has been released.

> A new plugin version has been published.
> Group: io.datapith.jayOverlay
> Plugin id: io.datapith.jayOverlay
> Version: 0.1.4
> If you have not published it, make sure to reset your publishing keys.

> You may delete the plugin within 7 days following its publication, afterward you can use https://github.com/gradle/plugin-portal-requests for issues/request or use [plugin-portal-support@gradle.com](mailto:plugin-portal-support@gradle.com) for security sensitive things.

When I go into the portal however, I see the status of the plugin is `approval pending` and the latest version is 0.1.0

### Expected Behavior

Latest version of plugin should be 0.1.4

### Current Behavior

Version of plugin is 0.1.0

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Fixed, both versions are published.

**Comment by msche** [comment]
thanks @ov7a . I think the portal could be improved by providing more feedback/insight. Would be helpfull for example to explain why the plugin is pending approval. I released for example already twice the plugin and the third time this approval kicked in.

**Comment by ov7a** [comment]
@msche Thanks for the feedback! I totally agree. Unfortunately, the plugin portal is out of the team's focus for now, and our capacity is limited.
