### ISSUE TITLE
Question: Is this an acceptable public plugin?

### ISSUE THREAD

**Issue by mbcoder** [gradle/plugin-portal-requests#198]
I wanted to find out if a submission for a new gradle plugin is acceptable.

I've been recommended to post the question here from this forum [post](https://discuss.gradle.org/t/will-my-plugin-be-allowed/46636).

I’m in the process of developing a gradle plugin to assist developers building JavaFX applications who use a mapping / GIS library I maintain.

I’ve been reading the publishing approval [page](https://plugins.gradle.org/docs/publish-plugin#approval) and it says:

> Plugins that are too specific to a particular use case or company will be rejected. Consider publishing it to a private Maven or Ivy repository if that is the case.

The plugin isn’t specific to a particular use case, but it will be specific to the library the company I work for publish. This [git repository](https://github.com/Esri/java-gradle-starter-project) is an example application using my library.

I basically don’t want to go through the publishing process only to find it is rejected at the last hurdle.

Thanks

**Comment by ov7a** [comment]
Hey Mark! Thank you for your interest in Gradle!

If the library you referring to is public and can be used by the community, then I think it is ok to publish the complimentary plugin on the Plugin Portal.

**Comment by mbcoder** [comment]
@ov7a thanks for the prompt reply - you'll see a new plugin shortly.

**Comment by mbcoder** [comment]
@ov7a I just had one last question.  Does the source code for the plugin need to be in a public github repository or is it acceptable for it to be in a private one?

Either is fine with me, I just want to follow the recommended practices.  

The [doc](https://docs.gradle.org/current/userguide/custom_plugins.html) for writing plugins is really good by the way.

**Comment by ov7a** [comment]
Thanks for the feedback! 

You can also refer to the [Plugin Portal Documentation](https://plugins.gradle.org/docs/publish-plugin#approval). 

The plugin should be open-source and publicly available, and we rarely make exceptions. So please, use a public GitHub repository unless you have a very good reason against it.
