### ISSUE TITLE
Publishing fails with "Unauthorized" despite valid API key

### ISSUE THREAD

**Issue by lberrymage** [gradle/plugin-portal-requests#199]
### Expected Behavior

`./gradlew publishPlugins` should publish a new plugin version when configured with a valid API key in `~/.gradle/gradle.properties`. This fails regardless of whether the API key is configured there or via `GRADLE_PUBLISH_KEY` and `GRADLE_PUBLISH_SECRET`.

### Current Behavior

`./gradlew publishPlugins` fails with an Unauthorized error as shown below.

```
> Task :bundletool-gradle-plugin:publishPlugins FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bundletool-gradle-plugin:publishPlugins'.
> Unauthorized!
    Login from command line using:
      gradle login
    or login and download user API keys on:
      https://plugins.gradle.org/user/login
```

### Context

I'm trying to publish a new version of one of our existing plugins on the Gradle plugin portal.

### Steps to Reproduce 

1) Create a plugin on the Gradle plugin portal
2) Attempt to upload a new version

### Your Environment

N/A

**Comment by ov7a** [comment]
Sorry for the late reply.

Sorry that you're having trouble with Gradle!

This feature works (we still receive new plugins), so I guess that this is an environment problem on your side.

Please, reach the [community](https://help.gradle.org/) in order to sort this out.
