### ISSUE TITLE
Publication to plugin portal failed for `org.kordamp.gradle.jandex`

### ISSUE THREAD

**Issue by aalmiray** [gradle/plugin-portal-requests#20]
Publishing version `0.2.0` of the jandex-gradle-plugin failed with a weird error stating that the given version was already published (which it wasn't).

### Expected Behavior
Successful publication to the Gradle Plugin portal.

### Current Behavior
Publication failed with 

	Publishing plugin org.kordamp.gradle.jandex version 0.2.0

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':publishPlugins'.
	> Failed to post to server.
	  Server responded with:
	  Plugin: 'org.kordamp.gradle.jandex', version: '0.2.0' exists already. It was created: 2019-11-26 11:34:38.333

### Context
Attempted to release version `0.2.0` of this plugin.

### Steps to Reproduce 
It'd be tricky to reproduce on production as version `0.2.0` indeed appears top exists after the fact. Perhaps it can be reproduced on a staging environment. Checkout https://github.com/aalmiray/jandex-gradle-plugin and publish tags `0.1.0` and `0.2.0`.
 
### Your Environment
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Mac OS X 10.14.4 x86_64

**Comment by lacasseio** [comment]
I transferred the issue to the Plugin Portal request board. I hope we can look into this very soon.

**Comment by aalmiray** [comment]
Thanks @lacasseio. This appears to be a duplicate of #9. FWIW I had the same problem when publishing clirr-gradle-plugin version `0.30.1`.

**Comment by lacasseio** [comment]
Could you confirm if the plugin binaries are published on Bintray as opposed to the plugin portal (aka using the `mavenCoordinate` block)?

**Comment by lacasseio** [comment]
It may be the same bug, but will likely require manual steps to fix the publication of this plugin. If you have another plugin that is having issue with the publication, please open another issue so we don't lose track of the individual things that needs fixing.

**Comment by aalmiray** [comment]
I publish to Bintray first, then to the Plugin Portal, using the same coordinates. I've been doing this for more than a year with all releases of the Kordamp plugin suite and only faced problems until just recently.

**Comment by lacasseio** [comment]
Perfect, thanks for confirming. It seems to be centralized around plugins published to Bintray. We will try to resolve this as soon as possible.

**Comment by tomdcc** [comment]
Hi @aalmiray 

Our server logs definitely show multiple attempts to publish this plugin:
- First at `Dec 5 18:51:27 UTC`, which succeeded
- Second at `Dec 5 18:51:31 UTC` which failed, due to the version already being published.

Both were published via the normal upload-to-the-portal mechanism, not via our Bintray syncing.

FWIW we don't have any retry mechanism in the plugin publishing plugin.

Do you have any logs from your plugin suite upload mechanism that might show more? I don't see the publishing plugin included in the source for your plugin that you linked to above - are you configuring it in unusually in any way?

**Comment by aalmiray** [comment]
The plugin relies on the `publish-plugin` but does it by applying the `org.kordamp.gradle.plugin`  plugin that configures it with some sensible defaults. I've been using the kordamp plugin for more than 7 months without a problem until just recently.

Publication is made first to Bintray then to the plugin portal, within the same command session, that is ` gw bintrayUpload publishPlugins`.

I also use this setup for publishing the kordamp plugins (30+ of them) and recently got the same problem when publishing `org.kordamp.gradle.clirr` version `0.30.1`, but not with `0.30.2`, `0.30.3`, and `0.30.4`, thus the error does not look deterministic in nature, at least to me.

Regarding logs, sadly no, I don't have any when the failure occurred.

**Comment by lacasseio** [comment]
Let's try to track each plugin publishing errors as different issues. I have the feeling there are several errors/issues getting in the way that may be different between plugins. To ensure we can keep track of each one, I created another issue for the publication issues of `org.kordamp.gradle.clirr`: https://github.com/gradle/plugin-portal-requests/issues/24

**Comment by lacasseio** [comment]
Let's focus this issue on `org.kordamp.gradle.jandex` (https://plugins.gradle.org/plugin/org.kordamp.gradle.jandex).

**Comment by lacasseio** [comment]
Sorry for the confusion, it doesn't seem to be related to any Bintray sync as this plugin was published on the plugin portal and no Bintray sync entry is configure (and we won't configure any as it's a decommissioned part of the plugin portal). Instead, what I can see is three versions have being published to the plugin portal (https://plugins.gradle.org/m2/org/kordamp/gradle/jandex-gradle-plugin/). Could you point out what is wrong with those versions? All of them seems to have the right files published. Is there any issue with consuming the plugins?

**Comment by aalmiray** [comment]
There's nothing wrong with those versions to the extent of my knowledge. All I know is that publication to the GPP gave the aforementioned error when publishing version `0.2.0` for the first time. Publication to GPP occurred after publication to Bintray was performed (with `bintray.publish = false` btw).

**Comment by lacasseio** [comment]
Unfortunately, it seems we are chasing a non-error. As pointed out by Tom the plugin somehow got published twice. The second time give the proper error. I would verify the publication process to ensure it's not trying to publish the plugin twice due to some misconfiguration of Gradle.
