### ISSUE TITLE
Transfer plugin com.apollographql.apollo3 to user Apollo

### ISSUE THREAD

**Issue by martinbonnin** [gradle/plugin-portal-requests#201]
Can you please transfer plugin com.apollographql.apollo3 from user [mbonnin](https://plugins.gradle.org/u/mbonnin) to user [Apollo](https://plugins.gradle.org/u/Apollo)

### Plugin Id
[com.apollographql.apollo3](https://plugins.gradle.org/plugin/com.apollographql.apollo3)

### Current Plugin Owner
[mbonnin](https://plugins.gradle.org/u/mbonnin) 

### Expected Plugin Owner
[Apollo](https://plugins.gradle.org/u/Apollo)

### Context
I (mbonnin) created this plugin a long time ago and would like to transfer it to an organization based email account in case I'm hit by a bus (hopefully not too soon!)

**Comment by jbartok** [comment]
Sent a request for confirmation to the registered email address. I can make the change once I get the reply.

**Comment by jbartok** [comment]
Ownership has been transferred. 

Can you please change the user name of the Apollo user ID from "Gradle" to something more specific (less confusing)>
