### ISSUE TITLE
Transfer dev.sigstore:sigstore-java to user: sigstore-java-releasers

### ISSUE THREAD

**Issue by loosebazooka** [gradle/plugin-portal-requests#204]
### Plugin Ids

[dev.sigstore.sign](https://plugins.gradle.org/plugin/dev.sigstore.sign)
[dev.sigstore.sign-base](https://plugins.gradle.org/plugin/dev.sigstore.sign-base)

### Current Plugin Owner

[vlsi](https://plugins.gradle.org/u/vlsi)
github: @vlsi

### Expected Plugin Owner

[sigstore-java-releasers](https://plugins.gradle.org/u/sigstore-java-releasers)
this includes @vlsi and @loosebazooka

### Context

sigstore-java-releasers is a group that allows anyone on the sigstore-java team to do releases. This includes current owner vlsi.

**Comment by ljacomet** [comment]
This was discussed in person, so ✅ 

Done
