### ISSUE TITLE
Remove io.github.yannickrobin.easyplugin

### ISSUE THREAD

**Issue by YannickRobin** [gradle/plugin-portal-requests#205]
### Plugin Id
io.github.yannickrobin.easyplugin

### Current Plugin Owner
[YannickRobin](https://github.com/YannickRobin)

### Context
I changed the name of the plugin. It was before https://plugins.gradle.org/plugin/io.github.yannickrobin.easyplugin.
This is now https://plugins.gradle.org/plugin/io.github.yannickrobin.easy-gradle-plugin.
My project is not released yet so the easyplugin is not used yet.

**Comment by ov7a** [comment]
Deleted.
