### ISSUE TITLE
Add docs on how to use environment variables for publish credentials

### ISSUE THREAD

**Issue by fourlastor** [gradle/plugin-portal-requests#206]
### Expected Behavior

https://plugins.gradle.org/docs/publish-plugin currently this doc doesn't mention one can use `GRADLE_PUBLISH_KEY`/`GRADLE_PUBLISH_SECRET` as environment variables instead of the gradle properties, I personally found it out by accident when using the `--validate-only` flag.

It would be nice to add a line to the docs explaining that's also an option, since it's much simpler to setup in a CI environment ([example](https://github.com/fourlastor-alexandria/construo/blob/main/.github/workflows/ci.yml#L28C11-L29)).

I know this is not a feature request, sorry for the wrong tag, I thought this was the closest to what I actually wanted to suggest

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address. However, this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by fourlastor** [comment]
If it's open source and you can point me at where it's hosted I'm also happy to do a pr

**Comment by ov7a** [comment]
Thanks for the suggestion! Unfortunately, Plugin Portal is not open source (at least for now), so the change can be made only by a team member.

**Comment by ov7a** [comment]
This is fixed:
https://plugins.gradle.org/docs/publish-plugin
