### ISSUE TITLE
Received email plugin published but portal keeps saying Pending Approval

### ISSUE THREAD

**Issue by FlyJingFish** [gradle/plugin-portal-requests#207]
A new plugin version has been published.
Group: io.github.FlyJingFish.AndroidAop
Plugin id: io.github.FlyJingFish.AndroidAop.android-aop
Version: 1.2.4
If you have not published it, make sure to reset your publishing keys.

You may delete the plugin within 7 days following its publication, afterward you can use https://github.com/gradle/plugin-portal-requests for issues/request or use [plugin-portal-support@gradle.com](mailto:plugin-portal-support@gradle.com) for security sensitive things.

Greetings,
The Gradle Team
[https://gradle.org](https://mandrillapp.com/track/click/30482292/gradle.org?p=eyJzIjoiQlFEbGdjcTRaMVB2eWF4dUJQMmFmT3J2aVFJIiwidiI6MSwicCI6IntcInVcIjozMDQ4MjI5MixcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dyYWRsZS5vcmdcIixcImlkXCI6XCIwYjViNWRmNGQyYmU0MDFhYjdiNjBiYWY5OThhZDU3NlwiLFwidXJsX2lkc1wiOltcIjQ2MjU2YmMxOTM5MmVjZTg2NGEyMDZmMGIzNmRjNDhhNDdkOWRjYzhcIl19In0)

**I received an email that the plugin was successfully published, but the plugin status is still "Pending Approval"**

**Comment by cobexer** [comment]
Sorry for the long delay for the review!

***
I just wanted to let you know that you should have received an email explaining the reason for the reject.
