### ISSUE TITLE
Remove io.github.dwarfley.versioncompanion

### ISSUE THREAD

**Issue by Dwarfley** [gradle/plugin-portal-requests#208]
### Plugin Id
[io.github.dwarfley.versioncompanion](https://plugins.gradle.org/plugin/io.github.dwarfley.versioncompanion)

### Current Plugin Owner
[Dwarfley](https://github.com/Dwarfley)

### Context
The plugin id has changed to [io.github.dwarfley.version-companion](https://plugins.gradle.org/plugin/io.github.dwarfley.version-companion) and the old plugin should be deleted.

**Comment by ljacomet** [comment]
Hey,

We do not delete plugins as this could break any user of said plugin out there.
We can however edit the description to point to the new plugin.

Are you OK with this?

**Comment by Dwarfley** [comment]
That's ok. Is there any way to mark it as deprecated or archived in my plugin list? If not, that's fine too.

**Comment by Dwarfley** [comment]
Any updates?

**Comment by ljacomet** [comment]
The description has been edited on the [deprecated plugin](https://plugins.gradle.org/plugin/io.github.dwarfley.versioncompanion).

The same description is visible in your plugin list.

We do not have a tagging or visual clue for deprecated / replaced plugins at this stage.
