### ISSUE TITLE
Wrong Gravatar usage on plugins.gradle.org

### ISSUE THREAD

**Issue by Vampire** [gradle/plugin-portal-requests#21]
I'm not sure whether this is the appropriate place to report this, so sorry if not.
https://plugins.gradle.org/u/Vampire does not show my assigned Gravatar.
This is caused by not following the rules described at https://de.gravatar.com/site/implement/hash/.
Specifically, the generated hash is from the e-mail address as-is instead of lowercased.
The used hash is `2ea6fcba24a569da6b4b546f9a62917d` which is the hash of `Bjoern@Kautler.net`, but the hashing algorithm should first lower-case the address to `bjoern@kautler.net` before the hash is calculated.

**Comment by big-guy** [comment]
I forgot that we snuck a fix for this in a few months ago.  Thanks for noticing this @Vampire
