### ISSUE TITLE
Not receiving emails from plugin-portal-support@gradle.com

### ISSUE THREAD

**Issue by pazlavi** [gradle/plugin-portal-requests#213]
Hi Gradle team, 
On Jan 31, we published our plugin, which was rejected because of domain verification and VCS URL.
On Feb 4, we sent an email to plugin-portal-support@gradle.com to verify our domain and ask to approve it as a property without a VCS URL that points to the source code. 
Unfortunately, we received no feedback except automatic confirmation that the email was received. 
Last week, we tried to re-publish our plugin. This time, we have yet to receive any publishing confirmation. The status in the dashboard account is still `Pending Approval`.

We would like to get your help with publishing our plugin. 

Group: `com.appsflyer`
Plugin id: `com.appsflyer.security`

Thanks.

**Comment by ljacomet** [comment]
Sorry for the delay in answering your request, see answer by email.
