### ISSUE TITLE
Pending Plugin removed after two days

### ISSUE THREAD

**Issue by kmbisset89** [gradle/plugin-portal-requests#215]
I submitted a plugin for verification 2 days ago and I was tracking its pending state. Then it disappeared this morning. My other plugin was still there. I checked my email to see if it was reject and saw no evidence. I ran the build again and it is back pending now.

### Expected Behavior
Plugin pending should always be shown else give the user a notification.

### Current Behavior
This sounds like a one off problem, but it was very odd. 

### Context
It may have slowed down my use of this plugin. I do not know if I got reset in some queue.

### Steps to Reproduce 
Submit a plugin and wait?

**Comment by ljacomet** [comment]
Hello,

A rejection email was sent on April 3, 2024 to the email address in your user profile on the plugin portal.
Follow the instructions there to get the plugin approved.

If you no longer have access to that email, let us know.

**Comment by cobexer** [comment]
A new plugin submission resolved the noted problems and got approved.
