### ISSUE TITLE
Transfer `measure-builds` plugin ownership

### ISSUE THREAD

**Issue by wzieba** [gradle/plugin-portal-requests#216]
### Plugin Id

`com.automattic.android.measure-builds` 

### Current Plugin Owner

`wzieba`

### Expected Plugin Owner

`automattic`

### Context

I've published the plugin to my personal account, while it should be owned by an organization account.

**Comment by cobexer** [comment]
https://plugins.gradle.org/plugin/com.automattic.android.measure-builds transferred to https://plugins.gradle.org/u/automattic
