### ISSUE TITLE
Change description of plugin org.cthing.locc

### ISSUE THREAD

**Issue by baron1405** [gradle/plugin-portal-requests#218]
Please change the description of the plugin [org.cthing.locc](https://plugins.gradle.org/plugin/org.cthing.locc) to:

```
Counts lines of code in a project using the fast and highly accurate locc4j library (https://github.com/cthing/locc4j). Supports over 250 computer languages and properly handles nested comments and embedded languages (e.g. CSS in HTML).
```

For verification, I am the owner of the plugin and I own the cthing.org domain.

Thanks,
Baron

**Comment by baron1405** [comment]
Is there an ETA for this request? I want to make sure I did not miss adding some label or other information.

**Comment by baron1405** [comment]
@cobexer would you be able to help resolve this issues?

**Comment by baron1405** [comment]
@ljacomet  Do you need additional information to make the change to the plugin description?

**Comment by ljacomet** [comment]
Hi @baron1405 ,

Your account on the plugin portal is not linked to GitHub.

Can you please email us from the plugin portal account email to request this?

**Comment by ljacomet** [comment]
Please clarify if you want the top level plugin description, the version description or all two to be updated as well.

**Comment by baron1405** [comment]
I just emailed plugin-portal-support@gradle.com from the email account I use on the portal. Please change only the top level description. Thanks!

**Comment by baron1405** [comment]
@ljacomet Did you receive the email and is there anything else holding up this change?

**Comment by ljacomet** [comment]
Thanks for the email and sorry for the delay.

This has been done.
