### ISSUE TITLE
Please change the description of my plugin

### ISSUE THREAD

**Issue by nagyesta** [gradle/plugin-portal-requests#219]
Hi,

I have made a typo/copy-paste issue  when I originally published https://plugins.gradle.org/plugin/io.github.nagyesta.run-dash-license-tool-gradle-plugin

Could someone please change the description for me? 

Please change from:
> Adds a convenient task to run the Run Dash License Tool on your Gradle build

To:
> Adds a convenient task to run the Dash License Tool on your Gradle build

Thank you!

**Comment by ov7a** [comment]
Sorry for the late reply. Done.

**Comment by nagyesta** [comment]
Thank you!
