### ISSUE TITLE
Change source URL and #tags for com.gitlab.svg2ico

### ISSUE THREAD

**Issue by markslater** [gradle/plugin-portal-requests#220]
I've move the source of [com.gitlab.svg2ico](https://plugins.gradle.org/plugin/com.gitlab.svg2ico) to https://github.com/svg2ico/svg2ico.  Could you update the Sources URL in the Plugin Portal for me?

Could you also add the #png tag in addition to the existing tags?

Thanks!

**Comment by ljacomet** [comment]
Hi,

We have no way of confirming this request is legit. 

Can you please request this by email to `plugin-portal-support @ gradle.com` using the email of the account owning the plugin?

**Comment by ljacomet** [comment]
Done, thanks for the validation.
