### ISSUE TITLE
Publishing suddenly fails with "VCS Url is not matching with the pluginId"

### ISSUE THREAD

**Issue by SgtSilvio** [gradle/plugin-portal-requests#221]
### Expected Behavior

Publishing a new version of an already existing plugin should not start to fail although it worked previously with the same plugin id.

### Current Behavior

```
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  VCS Url is not matching with the pluginId
```
Full log: https://github.com/SgtSilvio/gradle-oci/actions/runs/9317789173/job/25650885046

### Context

I am unable to publish a new version of the Gradle OCI Plugin (https://github.com/SgtSilvio/gradle-oci).
Already tried to find out the problem with debug logging, but I don't get more information than it fails because the plugin portal returns a 403 with the message "VCS Url is not matching with the pluginId".

### Steps to Reproduce 

This can be reproduced with rerunning the GitHub workflow: https://github.com/SgtSilvio/gradle-oci/actions/runs/9317789173/job/25650885046

### Your Environment

Publishing via GitHub Actions

**Comment by SgtSilvio** [comment]
I might have found the issue.
My GitHub name `SgtSilvio` includes uppercase letters, so the vcs url is `https://github.com/SgtSilvio/gradle-oci.git`.
The plugin id starts with `io.github.sgtsilvio`.
It seems the comparison of `SgtSilvio` and `sgtsilvio` does not work anymore, but it did previously, so I would consider this a regression.

The last time I published a plugin (https://github.com/SgtSilvio/gradle-metadata/releases/tag/v0.6.0) was 2 weeks ago and back then it still worked.

**Comment by fourlastor** [comment]
Having a similar issue with https://plugins.gradle.org/plugin/io.github.fourlastor.construo

The latest release run: https://github.com/fourlastor-alexandria/construo/actions/runs/9416647187/job/25940212839

In my case, the VCS url is pointing to an org I use to organise my repositories (so not just a text case issue), which up until last release was working (and the plugin portal correctly shows the GitHub url in version 1.1.1)

**Comment by ljacomet** [comment]
Sorry for the late reply

This was caused by a change on our side that looked good on paper ... but is wrong in practice.

We are working on fixing that. Please be patient with us for now. As soon as the fix is live, we will update this issue and your plugin should be accepted by the Gradle Plugin Portal.
