### ISSUE TITLE
Remove plugin "buildinfo", still pending approval.

### ISSUE THREAD

**Issue by KaustubhKhati** [gradle/plugin-portal-requests#226]
### Plugin Id
com.tesco.customerorder.common.buildinfo

### Current Plugin Owner
Kaustubh Khati

### Context
Hi, I by mistake published 2 plugin (they are same but different package). Can you please delete the plugin "com.tesco.customerorder.common.buildinfo". It is pending approval, i dont see any option to delete it from my end hence raising the ticket.

**Comment by ov7a** [comment]
Deleted
