### ISSUE TITLE
Removal: Clean Wizard Gradle Plugin

### ISSUE THREAD

**Issue by timplifier** [gradle/plugin-portal-requests#229]
### Plugin Id
io.github.timbermir.cleanwizard

### Current Plugin Owner
timbermirincorporation@gmail.com

### Context
https://github.com/Timbermir/clean-wizard
I request plugin removal due to group change. It used to be `io.github.timbermir.cleanwizard`, but now I have published another plugin with group `io.github.timbermir.clean-wizard` so plugin with old group is useless

**Comment by cobexer** [comment]
We usually do not delete plugins in such situations.

The plugin versions in question were all pre-release versions and had no downloads so I went ahead and deleted them anyway.

Please do not expect such requests to be fulfilled in the future - especially if the change in plugin id is this small!
