### ISSUE TITLE
Synchronize `jruby-gradle-core-plugin` with to the plugin portal

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#23]
See https://discuss.gradle.org/t/syncing-a-new-plugin-from-bintray/32184

**Comment by lacasseio** [comment]
The request seems to have being received, waiting for it to be accepted: https://github.com/gradle/gradlecom/issues/598

**Comment by lacasseio** [comment]
The bintray repository for the plugin isn't included on JCenter. Responded to the thread so this can be fixed.

**Comment by ysb33r** [comment]
I only realised that JCenter is also needed. Just sent the request.

**Comment by lacasseio** [comment]
Awesome, as soon as it's approved by JCenter then the plugin should appear in the plugin portal over the next hour.

**Comment by ysb33r** [comment]
Hey, it's there!

Doing some final tests with other project, then I can close this.

**Comment by lacasseio** [comment]
I can see the plugin is on the portal: https://plugins.gradle.org/plugin/com.github.jruby-gradle.core

I can confirm the plugin can be downloaded. I will go ahead and close the issue. If there is any problem, just reopen the issue with more information.

**Comment by ysb33r** [comment]
Thanks for finally solving this issue for us! You have helped a lot of people indirectly.
