### ISSUE TITLE
Version removal of plugin 'com.hanggrian.pages'

### ISSUE THREAD

**Issue by hanggrian** [gradle/plugin-portal-requests#230]
Hi Gradle support,

While testing the plugin, I frequently delete a version and replace it with a new upload of the same version. In my last attempt, I was unable to republish the plugin despite successfully deleting the version:

```
> Failed to post to server.
  Server responded with:
  Plugin: 'com.hanggrian.pages', version: '0.1' exists already. It was created: 2024-08-05 18:13:53.897
```

A search of the plugin [returns empty](https://plugins.gradle.org/plugin/com.hanggrian.pages) because there is no other version.

Should I release my plugin under version `0.1` or increment it to `0.2`?

Thanks for your help.

### Plugin Id

`com.hanggrian.pages:0.1`

### Current Plugin Owner

- Username: **hanggrian**
- Email: **hanggrian@proton.me**

**Comment by cobexer** [comment]
It looks like version `0.1` was not uploaded completely and is marked as "existing, but broken" on the plugin portal (and thus hidden from the public).

I deleted the broken version now.
I would also like to point out that deleting a plugin version is very bad, especially when reusing the version number:
The Gradle Plugin Portal is usually not accessed directly but instead accessed through a caching proxy repository service (like JFrog Artifactory or Sonatype Nexus, ...). Such a cache may never update an artifact if it is already stored in itself (identified by version number) ... so any of your published artifact revisions may be used and your fixes may never reach your users there.

**Comment by hanggrian** [comment]
Thanks for the explanation. In the future, I'll be sure to only delete a version under emergency circumstances.
