### ISSUE TITLE
Removal: Clean Wizard Multi Module Plugin

### ISSUE THREAD

**Issue by timplifier** [gradle/plugin-portal-requests#231]
### Plugin Id
io.github.timbermir.cleanwizard.multimodule

### Current Plugin Owner
timbermirincorporation@gmail.com

### Context
I request the `io.github.timbermir.cleanwizard.multimodule` plugin remova due to group change. It is now changed to `io.github.timbermir.clean-wizard.multimodule`. Plugin with new group is already published so I want old plugin to be removed. I'm sorry for such requests but apparently old plugin has no downloads and it is not a release version

**Comment by cobexer** [comment]
Done.
