### ISSUE TITLE
Trailing slash issue when GPP accessing directory

### ISSUE THREAD

**Issue by Talavera316** [gradle/plugin-portal-requests#232]
For http get at GPP directory with the trailing slash, for example:
https://plugins.gradle.org/m2/org/sonarsource/scanner/api/sonar-scanner-api/

getting a redirection with malformed URL (double slash before “org”)
https://repo.maven.apache.org/maven2//org/sonarsource/scanner/api/sonar-scanner-api/

when there is no trailing slash:
https://plugins.gradle.org/m2/org/sonarsource/scanner/api/sonar-scanner-api
the redirection works nice
https://repo.maven.apache.org/maven2/org/sonarsource/scanner/api/sonar-scanner-api/

Is it intentional or just a side effect?
Björn Kautler's (Vampire)
 comment to the issue discussion
I would assume this is a bug, maybe introduced with the change to redirect to MC instead of JC.

**Comment by ov7a** [comment]
Thanks, we'll fix that soon.
FTR, this bug unrelated with the switch to Maven Central and was introduced earlier (at the end of June).

**Comment by ov7a** [comment]
This was fixed.
