### ISSUE TITLE
Support redirecting the old plugin id to the new one

### ISSUE THREAD

**Issue by Goooler** [gradle/plugin-portal-requests#233]
### Expected Behavior

The Shadow plugin project has been transferred from `johnrengelman/shadow` to `GradleUp/shadow`, and we published a new plugin id for it, from `com.github.johnrengelman.shadow` to `com.gradleup.shadow`, Maven coordinates also changed, see more details at https://github.com/GradleUp/shadow/releases/tag/8.3.0.

It would be very handy if Plugin Portal could redirect the old plugin id to the new one to notify older version users to track the newer updates. At least, we can link the new plugin page in the old one.

### Current Behavior

- Old: https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow
- New: https://plugins.gradle.org/plugin/com.gradleup.shadow

### Context

https://github.com/GradleUp/shadow/issues/938

**Comment by ov7a** [comment]
Plugin Portal does not have this kind of functionality, and we don't plan to add support for it.

From the PP perspective, those two are different plugins. 

I've updated the description of the old plugin so it's easier for users to navigate to it.

**Comment by Goooler** [comment]
Thanks for doing this.
