### ISSUE TITLE
transfer ownership of org.aim42.htmlSanityCheck

### ISSUE THREAD

**Issue by gernotstarke** [gradle/plugin-portal-requests#234]
### Plugin Id
org.aim42.htmlSanityCheck

### Current Plugin Owner
https://plugins.gradle.org/u/gernotstarke

Dr. Gernot Starke, previous e-mail gs@gernotstarke.de, current e-mail gernot.starke@mailbox.org

### Expected Plugin Owner
[
https://plugins.gradle.org/u/GerdAschemann

Gerd Aschemann,

### Context

no idea what I shall do here.
Gerd Aschemann shall be the new owner :-)

**Comment by ov7a** [comment]
Done.

P.S.
> no idea what I shall do here.

You could provide some history in that field, e.g. why it happened this way that the author is different:)
