### ISSUE TITLE
Transfer ownership of com.ssn.versioneer plugin

### ISSUE THREAD

**Issue by pbtanna17** [gradle/plugin-portal-requests#235]
The plugin is owned by [Geoffrey WAROQUIER](https://plugins.gradle.org/u/gwaroquier) who has left the company SSNI now Itron Inc. for quite some time. We only had to edit the plugin now as it's giving some issues(variable name build, commit length inconsistency). I want to make the edits to the plugin so that we can seamlessly keep using it for our purpose. 
Here is my [linkedin](https://www.linkedin.com/in/pbtanna17/) profile, which shows that I am still working with the company.
Do let me know if I can be of any assistance in getting this transition over smoothly and quickly.

Plugin id: [com.ssn.versioneer](https://plugins.gradle.org/plugin/com.ssn.versioneer)
Current plugin owner: [Geoffrey WAROQUIER](https://plugins.gradle.org/u/gwaroquier)
Expected plugin owner: [Parth Tanna](https://plugins.gradle.org/u/pbtanna17)

**Comment by ov7a** [comment]
If the company wants to take over this plugin, we would need something more than just linkedIn profile to do so. We need to validate domain ownership ("ssn.com"). Please contact us [via email](https://plugins.gradle.org/docs/get-help) so we can proceed.
