### ISSUE TITLE
Transfer to gradleup user

### ISSUE THREAD

**Issue by martinbonnin** [gradle/plugin-portal-requests#236]
Hi 👋 

Can the following plugins be transferred to the [gradleup](https://plugins.gradle.org/u/gradleup) user (plugins@gradleup.com) ?

* com.gradleup.auto.manifest
* com.gradleup.gr8
* com.gradleup.gr8.external
* com.gradleup.shadow
* com.gradleup.static-analysis

Ping [@tasomaniac](https://github.com/tasomaniac) as the current owner of the plugins. Can you confirm you're ok with the change?

**Comment by tasomaniac** [comment]
Yes of course. I'm ok with the change.

**Comment by deepy** [comment]
And `com.github.gradlecommunity.jaxb2` as well, so we can make a final release and deprecate the old name

**Comment by ov7a** [comment]
Done!
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/41fec466-a313-4cbb-9dff-f92a0b4de908">

**Comment by martinbonnin** [comment]
Thanks!
