### ISSUE TITLE
Bug: Unable to upload new version (because previous attempt failed: `already in DB with a different hash`)

### ISSUE THREAD

**Issue by Rolf-Smit** [gradle/plugin-portal-requests#237]
I tried uploading a new version of my plugin, however that failed with the following message:

> Artifact nl.neotech.plugin:android-root-coverage-plugin:1.9.0 with type jar:javadoc already in DB with a different hash

This likely happened because I tried using Dokka to generate documentation for the plugin (since it is Kotlin), however the latest version of `com.gradle.plugin-publish` also generates javadocs on it's own. This may have lead to duplicated javadocs being uploaded.

Please note: version 1.9.0 does not exist on the Plugin Portal (it does not show, and I cannot delete it either)

However after removing Dokka from my upload configuration, the upload would not recover from this, it kept failing.

Only after I incremented the version number again the upload succeeded. However I removed that version again, because this is not a solution to me. Preferably I want to upload version 1.9.0 with Dokka javadocs.

Some more details about the setup:

I'm using both: `com.gradle.plugin-publish:1.2.2` and `com.vanniktech.maven.publish:0.29.0` (I previously used older versions). I'm also using Dokka (as previously mentioned) to generate Javadocs, `plugin-publish` previously did not generate any javadocs on it's own. Notice that I'm not using the default configuration from `vanniktech.maven.publish`, instead I used the following to have it generate javadocs using Dokka:
`configure(new GradlePlugin(new JavadocJar.Dokka("dokkaHtml")))`

**Comment by ljacomet** [comment]
Hey,

We cleaned up the state and have a ticket to make sure that duplicate artifacts (same content) keep failing as intended but without blocking the user from uploading a fixed publication.
