### ISSUE TITLE
Rejection with valid TXT record

### ISSUE THREAD

**Issue by davidparry** [gradle/plugin-portal-requests#240]
I followed the instructions and added a TXT record, but i still got rejected with the following email:
Hi,

We received your plugin submission for "ai.qodo".

Your plugin was flagged for manual review because of the following issue(s):

The group ID prefix 'ai.qodo' does not match the default GitHub domain for your username 'io.github.davidparry'. Please prove ownership of the "[qodo.ai](http://qodo.ai/)" domain by adding a TXT record with the value "gradle-verification=CIMDO88EU8G7FNUGT6SGTOJHQ49O6" to your DNS, or use a plugin ID that ties to your GitHub user ID, for example 'io.github.davidparry.cover-agent'.
Please refer to our documentation on plugin approval guidelines for more information: https://plugins.gradle.org/docs/publish-plugin#approval

Please resubmit your plugin once you have corrected these issues to be reconsidered for approval. Your plugin submission has been canceled, so you may reuse the same version number.

### Expected Behavior
Approved

### Current Behavior
Rejected

### Context
Can not publish plugin

### Steps to Reproduce - both commands below show the record
I did ➜  ~ nslookup -type=TXT qodo.ai
Server:		2001:1998:f00:1::1
Address:	2001:1998:f00:1::1#53

Non-authoritative answer:
qodo.ai	text = "google-site-verification=JsmG1i2yZXsWTfX_lO7RvlJ7S9aUcTeWTGFvKIcAV-c"
qodo.ai	text = "google-site-verification=Z0YxubQCrspXEOZV68IgCxuSz4I4tzwvhORPCDwxWc4"
qodo.ai	text = "gradle-verification=CIMDO88EU8G7FNUGT6SGTOJHQ49O6"
qodo.ai	text = "loaderio=1ef4fa230d7e79b9111c0e2e0406fdce"
qodo.ai	text = "v=spf1 include:_spf.google.com include:26816375.spf08.hubspotemail.net -all"

I also did command: dig txt qodo.ai +short    
"v=spf1 include:_spf.google.com include:26816375.spf08.hubspotemail.net -all"
"google-site-verification=JsmG1i2yZXsWTfX_lO7RvlJ7S9aUcTeWTGFvKIcAV-c"
"google-site-verification=Z0YxubQCrspXEOZV68IgCxuSz4I4tzwvhORPCDwxWc4"
"gradle-verification=CIMDO88EU8G7FNUGT6SGTOJHQ49O6"
"loaderio=1ef4fa230d7e79b9111c0e2e0406fdce"

**Comment by abstratt** [comment]
Indeed, my apologies. I still had the query on my console log, and can see now the record looked good, I just missed it.

Could you please retry publishing it so I can approve it?

**Comment by davidparry** [comment]
And done, thank you again for all your help!
David Parry
