### ISSUE TITLE
gradle failed with error Script 'node_modules\react-native\react.gradle' line: 366 Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

### ISSUE THREAD

**Issue by sumeetagarwal** [gradle/plugin-portal-requests#241]
Android react native build with gradle failed with error Script 'node_modules\react-native\react.gradle' line: 366
Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

Gradle build failed with 
Script 'node_modules\react-native\react.gradle' line: 366
Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

Build should run with app bundle 
### Expected Behavior

<html>
<body>
<div class="FailureItem__location" style="box-sizing: border-box; font: 400 14px / 20px Inconsolata, Monaco, &quot;Courier New&quot;, monospace; white-space: pre; padding-left: 24px; color: rgb(2, 48, 58); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Script 'C:\Users\agarsum\RealtimeAzure\mobile-client\featureBranch\1.1.0_UAT_MAC\rt-mobile-client\node_modules\react-native\react.gradle' line: 366</div><div class="FailureItem__message" style="box-sizing: border-box; padding-top: 8px; font: 400 14px / 20px Inconsolata, Monaco, &quot;Courier New&quot;, monospace; white-space: pre; padding-left: 24px; color: rgb(2, 48, 58); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.</div><div class="FailureItem__exception " style="box-sizing: border-box; padding: 32px 0px; color: rgb(2, 48, 58); font-family: Lato, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="FailureItem__exception-header" style="box-sizing: border-box; line-height: 20px; margin-bottom: 8px; padding-left: 24px;"><span class="FailureItem__exception-title" style="box-sizing: border-box; font-weight: 500;">Exception</span></div><div class=" FailureException" style="box-sizing: border-box; font: 14px Inconsolata, Monaco, &quot;Courier New&quot;, monospace;"><div style="box-sizing: border-box;">
  | org.gradle.api.GradleScriptException: A problem occurred evaluating script. |  
-- | -- | --

</div></div></div></div></div>
</body>
</html>

<html>
<body>
<div class="FailureItem__message" style="box-sizing: border-box; padding-top: 8px; font: 400 14px / 20px Inconsolata, Monaco, &quot;Courier New&quot;, monospace; white-space: pre; padding-left: 24px; color: rgb(2, 48, 58); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">compileSdkVersion is not specified. Please add it to build.gradle</div><div class="FailureItem__exception " style="box-sizing: border-box; padding: 32px 0px; color: rgb(2, 48, 58); font-family: Lato, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="FailureItem__exception-header" style="box-sizing: border-box; line-height: 20px; margin-bottom: 8px; padding-left: 24px;"><span class="FailureItem__exception-title" style="box-sizing: border-box; font-weight: 500;">Exception</span></div><div class=" FailureException" style="box-sizing: border-box; font: 14px Inconsolata, Monaco, &quot;Courier New&quot;, monospace;"><div style="box-sizing: border-box;">
  | org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'. |  
-- | -- | --

</div></div></div></div></div>
</body>
</html>

### Current Behavior

gradle version used 
![Image](https://github.com/user-attachments/assets/006ecfac-d7d2-472f-a1eb-924470332496)
![Image](https://github.com/user-attachments/assets/f265d774-b2eb-4ca6-985f-810fbd1d3774)
 Gradle build scan link -  https://gradle.com/s/b5gpbr4utg626

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.
