### ISSUE TITLE
Remove all plugins of version "0.6.0" under the package `com.huanshankeji`

### ISSUE THREAD

**Issue by ShreckYe** [gradle/plugin-portal-requests#243]
### Plugin Id

Plugin ID: `com.huanshankeji.*`
Version: 0.6.0

### Current Plugin Owner

Me (@ShreckYe, https://plugins.gradle.org/u/ShreckYe).

### Context

Identical to #239. Original comment at https://github.com/gradle/plugin-portal-requests/issues/239#issuecomment-2422664174.

**Comment by ljacomet** [comment]
This should be done. Update here in case a re-publish does not work.

**Comment by ShreckYe** [comment]
The problem is fixed. Thanks.
