### ISSUE TITLE
My plugin has not been published with a new version and has failed several times since then

### ISSUE THREAD

**Issue by heowc** [gradle/plugin-portal-requests#246]
### Expected Behavior

Version 0.0.7 should be published

### Current Behavior

0.0.7 was not published properly, and the task still failed with 'Unauthorized!' message

### Your Environment

https://plugins.gradle.org/plugin/dev.heowc.heo

**Comment by ljacomet** [comment]
Hello,

Version 0.0.7 failed to publish properly.

You should be able to do that now.

**Comment by heowc** [comment]
> Hello,
> 
> Version 0.0.7 failed to publish properly.
> 
> You should be able to do that now.

I have confirmed that it was posted correctly.

Thank you for your quick response.
