### ISSUE TITLE
Ownership transfer of com.google.protobuf

### ISSUE THREAD

**Issue by zhangkun83** [gradle/plugin-portal-requests#25]
### Plugin Id
com.google.protobuf

### Current Plugin Owner
zhangkun83

### Expected Plugin Owner
voidzcy (both the Plugin Portal username and Github username)

### Context
@voidzcy is already the maintainer on the github project: https://github.com/google/protobuf-gradle-plugin

**Comment by voidzcy** [comment]
I acknowledge the transfer (or to be added as an co-owner).

**Comment by lacasseio** [comment]
I will add both of you as owners.

**Comment by lacasseio** [comment]
Both @voidzcy and @zhangkun83 should have access now. Happy developing!
