### ISSUE TITLE
Plugin publishing delays

### ISSUE THREAD

**Issue by nsoft** [gradle/plugin-portal-requests#26]
Plugin publishing seems to be stalled or not happening... Or perhaps the message about 24h turn around produced by the plugin is not accurate, and should be updated?

> The request should be processed within the next 24 hours, at which point you will be contacted via email.

See: https://discuss.gradle.org/t/plugin-pending-approval-since-before-xmas/34390/3

**Comment by lacasseio** [comment]
Thanks for opening this issue. This is something we have to change as this timeline is no longer exactly true. We would love to be able to provide a 24h turnaround but it's sometime not possible and this message is setting a false expectation. We need to change that message.
