### ISSUE TITLE
Ownership transfer of com.google.osdetector

### ISSUE THREAD

**Issue by zhangkun83** [gradle/plugin-portal-requests#27]
### Plugin Id
com.google.osdetector

### Current Plugin Owner
zhangkun83

### Expected Plugin Owner
voidzcy (both the Plugin Portal username and Github username)

### Context
[com.google.osdetector](https://github.com/google/osdetector-gradle-plugin) is the companion project of [com.google.protobuf](https://github.com/google/protobuf-gradle-plugin) of which @voidzcy is already the maintainer.

**Comment by voidzcy** [comment]
I acknowledge the transfer (or to be added as a co-owner).

**Comment by lacasseio** [comment]
I added @voidzcy as a co-owner. @zhangkun83 you still have the ownership over the plugin.
