### ISSUE TITLE
Remove "io.arrow-kt.arrow" plugin

### ISSUE THREAD

**Issue by rachelcarmena** [gradle/plugin-portal-requests#28]
### Plugin Id
[io.arrow-kt.arrow](https://plugins.gradle.org/plugin/io.arrow-kt.arrow)

### Current Plugin Owner
rachelmcarmena

### Note

All the content from https://plugins.gradle.org/m2/io/arrow-kt/ can be deleted, `arrow-kt` included.

### Context
We're going to publish this plugin from a different account and with a different roadmap. We don't want to keep the current versions.

_Thanks in advance!!_ :+1:

**Comment by rachelcarmena** [comment]
Please :pray:

**Comment by lacasseio** [comment]
We will do our best to action this request by end of the day tomorrow. Could you help us understand the adoption of your plugin? It's important for us to avoid bad user experience for users and if we see that it's highly used, it may be more complicated to remove without having some sort of deprecation in place. Note that if the plugin was recently published (less than a week) you can remove it via your user profile on the plugin portal.

**Comment by rachelcarmena** [comment]
> We will do our best to action this request by end of the day tomorrow. Could you help us understand the adoption of your plugin? It's important for us to avoid bad user experience for users and if we see that it's highly used, it may be more complicated to remove without having some sort of deprecation in place. Note that if the plugin was recently published (less than a week) you can remove it via your user profile on the plugin portal.

Thank you so much, @lacasseio !!! :The plugin is still not being used. Just small sandbox examples. It was published a few weeks ago (first version: 25 November 2019). 

We'd like to remove it because of these reasons:
- It was published from my personal account (that's wrong).
- We're going to change the version roadmap (just using Gradle Portal for release versions).

We think it's easier to remove it and to start the publication process from the right account.

Thanks again!!

**Comment by big-guy** [comment]
@rachelcarmena We could transfer the plugin to another account if need be.  Does it really need to be deleted if another account takes over?

**Comment by lacasseio** [comment]
Sorry about not executing on this yesterday. We verified the download count is low enough to avoid any impact. We will delete it tomorrow.

**Comment by lacasseio** [comment]
Actually, I moved ahead with deleting the plugins version that show up on the portal. There are still some things left over on our side that we need to confirm that won't interfere with your future release of the plugin.

**Comment by rachelcarmena** [comment]
> @rachelcarmena We could transfer the plugin to another account if need be. Does it really need to be deleted if another account takes over?

Thanks @big-guy!! It could be another option, however, we decided to delete it because we're going to start again from the beginning with a different version roadmap.

> Sorry about not executing on this yesterday. We verified the download count is low enough to avoid any impact. We will delete it tomorrow.

Nothing to apologize, thanks @lacasseio !!

> Actually, I moved ahead with deleting the plugins version that show up on the portal. There are still some things left over on our side that we need to confirm that won't interfere with your future release of the plugin.

Thanks!! I've seen that the plugin doesn't exist now. Please, let me know when those things are done from your side (maybe, just closing this issue) and we'll start again the publication process from a different account.

Thank you so much again!

**Comment by lacasseio** [comment]
We double checked everything and we can close this issue. If you have any issue when publishing your new version roadmap, feel free to open another issue here.

**Comment by rachelcarmena** [comment]
> We double checked everything and we can close this issue. If you have any issue when publishing your new version roadmap, feel free to open another issue here.

Thank you very much Daniel !! :tada: We're going to start the process again.

**Comment by rachelcarmena** [comment]
So sorry for disturbing you again... @lacasseio 

It seems something exists:

```
 > Failed to post to server.
  Server responded with:
  The user '47degci' does not have write permissions to plugin [io.arrow-kt.arrow]
```

**Comment by lacasseio** [comment]
I just gave ownership to the plugin group `io.arrow-kt` to `47degci`. It _should_ solve your issue.

**Comment by rachelcarmena** [comment]
Awesome @lacasseio :tada: It worked:

```
> Task :gradle-plugin:publishPlugins
Publishing plugin io.arrow-kt.arrow version 0.0.0
Publishing artifact build/libs/gradle-plugin-0.0.0.jar
Publishing artifact build/libs/gradle-plugin-0.0.0-sources.jar
Publishing artifact build/libs/gradle-plugin-0.0.0-javadoc.jar
Publishing artifact build/publications/pluginMaven/pom-default.xml
Activating plugin io.arrow-kt.arrow version 0.0.0
```

I really appreciate your kind attention.

Thank you so much!! I wish you all the best!!

**Comment by lacasseio** [comment]
No worries, I believe that plugin authors are very important to the Gradle community. Don't hesitate to use this issue tracker to open any other issues with your plugin or feature requests for improving the plugin portal experience.
