### ISSUE TITLE
Request to delete a SNAPSHOT version deployed to the portal

### ISSUE THREAD

**Issue by KengoTODA** [gradle/plugin-portal-requests#30]
### Plugin Id

jp.skypencil.spotbugs.snom

### Current Plugin Owner

@KengoTODA

### Context

Deployed [2.0.0-SNAPSHOT](https://plugins.gradle.org/plugin/jp.skypencil.spotbugs.snom/2.0.0-SNAPSHOT) version by my mistake, so want to request to remove it.
Refer https://discuss.gradle.org/t/request-to-delete-a-snapshot-version-deployed-to-the-portal/34430 for detsil.

**Comment by KengoTODA** [comment]
Hi, any update on this issue? This SNAPSHOT version is displayed as the latest release, even though it is not so.
I wish we can avoid users' confusion in the near future. Thanks in advance!

**Comment by big-guy** [comment]
Sorry, this got dropped.  I've deleted the snapshot version. Let me know if you see anything amiss.

**Comment by KengoTODA** [comment]
Confirmed the fix, thanks for your help!
