### ISSUE TITLE
Please remove https://plugins.gradle.org/plugin/io.jumpco.open.kfsm.gradle.viz-plugin

### ISSUE THREAD

**Issue by corneil** [gradle/plugin-portal-requests#32]
I have decided to make the name a little shorter by remove .gradle from the id.

### Plugin Id
https://plugins.gradle.org/plugin/io.jumpco.open.kfsm.gradle.viz-plugin

### Current Plugin Owner
corneil.duplessis@gmail.com or github @corneil

### Context
I have decided to make the name a little shorter by remove .gradle from the id.

The same plugin is published with a shorter name.

**Comment by big-guy** [comment]
Sorry, I thought someone had already taken care of this for you.  I've disabled the plugin now.
