### ISSUE TITLE
Remove versions 4.2.0, 4.3.0, and 4.3.1 of the biz.aQute.bnd.gradle plugins from portal

### ISSUE THREAD

**Issue by bjhargrave** [gradle/plugin-portal-requests#33]
Versions 4.2.0, 4.3.0, and 4.3.1 of the biz.aQute.bnd.gradle plugins are published in the plugin portal with pom files which prevent them from being properly used.

See https://github.com/gradle/plugin-portal-requests/issues/9.

A fix from @marcphilipp (https://github.com/bndtools/bnd/pull/3811) now enables us to publish with the proper pom to the plugin portal. 

I need to republish versions 4.2.0, 4.3.0, and 4.3.1 of the biz.aQute.bnd.gradle plugins, so please delete those versions from the plugin portal.

Note: I just published version 5.0.0 of the biz.aQute.bnd.gradle plugins using the fix from @marcphilipp, so that version is correct and does not need to be deleted.

### Plugin Id

There are 3 plugin ids `biz.aQute.bnd`, `biz.aQute.bnd.builder`, and `biz.aQute.bnd.workspace` for each of the 3 versions,  4.2.0, 4.3.0, and 4.3.1, that need to be deleted.

### Current Plugin Owner

I am the plugin owner. 
### Context

See https://github.com/gradle/plugin-portal-requests/issues/9#issuecomment-566445751 where it is suggested I open this bug to request deletion of the already published plugins with invalid pom files.

**Comment by ov7a** [comment]
Hi! Sorry for the late reply. This repository was out of our team's attention for a while. 

I'm closing this issue as stale. 

Note that our policy is to remove old plugin versions only if there is a security issue.
