### ISSUE TITLE
Transfer plugin com.widen.versioning to widen

### ISSUE THREAD

**Issue by sagebind** [gradle/plugin-portal-requests#34]
### Plugin Id

com.widen.versioning

### Current Plugin Owner

[sagebind](https://plugins.gradle.org/u/sagebind) (me)

### Expected Plugin Owner

[widen](https://plugins.gradle.org/u/widen) (@widendev on GitHub)

### Context

I created this plugin on behalf of Widen Enterprises as an employee. Now the Widen development team has a dedicated account on the Plugin Portal for publishing such plugins, so I'd like to transfer ownership from my personal account to the "official" Widen account.

**Comment by big-guy** [comment]
@sagebind This should be done - let me know if you run into any problems.

**Comment by sagebind** [comment]
Perfect, thanks!
