### ISSUE TITLE
Transfer ownership for org.jetbrains.kotlinx.knit plugin to kotlin

### ISSUE THREAD

**Issue by elizarov** [gradle/plugin-portal-requests#35]
### Plugin Id

`org.jetbrains.kotlinx.knit`

### Current Plugin Owner

`elizarov`

### Expected Plugin Owner

`kotlin`

### Context

I've been testing plugin publishing from my own account. After completing the testing I've deleted the plugin and I don't see it on my account page anymore. However, `kotlin` account cannot still upload it. The sources for the plugin (authored by me) are here: https://github.com/Kotlin/kotlinx-knit/blob/master/build.gradle.kts#L70-L80

**Comment by big-guy** [comment]
@elizarov This has been transferred.  Please let me know if you still have any problems.
