### ISSUE TITLE
Remove plugins `dev.gradleplugins.*`

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#36]
### Plugin Id

- `dev.gradleplugins.java-gradle-plugin`
- `dev.gradleplugins.groovy-gradle-plugin`
- `dev.gradleplugins.kotlin-gradle-plugin`

See: https://plugins.gradle.org/search?term=dev.gradleplugins

### Current Plugin Owner

- @lacasseio (aka me)

### Context

The Kotlin one never worked as expected due to how the `kotlin-dsl` plugin is integrated with Gradle. The other two are being released under Bintray for now until they become more stable for a wider audience.

Another reason why they should be removed is the plugin mostly doesn't work because the original TestKit test was all wrong due to how TestKit work and was hiding bugs after publication.

**Comment by big-guy** [comment]
@lacasseio I disabled all of the active versions of that plugin.  Let me know if this causes you any trouble.
