### ISSUE TITLE
Approval required for de.chkpnt.truststorebuilder

### ISSUE THREAD

**Issue by chkpnt** [gradle/plugin-portal-requests#38]
### Expected Behavior
As far as I understood the [publish-plugin](https://plugins.gradle.org/docs/publish-plugin), a manual approval by the Gradle team shouldn't be needed if the group ID isn't overwritten.

### Current Behavior
An approval is required for v0.4.0 of my Gradle plugin [de.chkpnt.truststorebuilder](https://plugins.gradle.org/plugin/de.chkpnt.truststorebuilder). Unfortunately, I do not remember if the previous versions needed an approval, too, or if it is a new behaviour.

### Context
I'm using the `groupId` _de.chkpnt_ and `artifactId` _truststorebuilder-gradle-plugin_.

### Steps to Reproduce 
The plugin has been published via the publish-plugin on Travis-CI. See lines 580-587 in the corresponding [build log](https://travis-ci.com/github/chkpnt/truststorebuilder-gradle-plugin/builds/160262968#L580-L587).

### Your Environment
chkpnt/truststorebuilder-gradle-plugin@ab351ba769faa1ce696de82586dc693bc8cf8034

**Comment by chkpnt** [comment]
Don't get me wrong, I'm not complaining about the outstanding approval.

I just would like to know, why an approval is needed in my case, or what I'd have to change, so that an approval isn't needed in the future.

**Comment by big-guy** [comment]
Sorry, that doc is wrong.  All new plugins require manual review before they show up on the plugin portal.

I've approved the requests, so you should be able to see it now.

**Comment by chkpnt** [comment]
Thanks for the approval and the clarification! So updates require an approval, too?

When you update the doc, please also update the [submit-page](https://plugins.gradle.org/docs/submit), where it says "Some plugins require manual acceptance [...]". On the doc for publish-plugin, I see three places which should be updated: The info box above the examples, the full example and the Kotlin example.
