### ISSUE TITLE
Adjust plugin descriptions and tags for `dev.nokee.*` plugins

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#41]
There seems to be no way to edit the description and tags for a plugin synched via Bintray. I would like to change the description, tag and website as follow:

### `dev.nokee.cpp-language`
Description: Provides C++ language compilation to Nokee plugins; see the documentation to learn more.
Tags: gradle-native, native, cpp, c++, nokee
Website: https://nokee.dev/docs/cpp-language-plugin

### `dev.nokee.c-language`
Description: Provides C language compilation to Nokee plugins; see the documentation to learn more.
Tags: gradle-native, native, c, nokee
Website: https://nokee.dev/docs/c-language-plugin

### `dev.nokee.objective-cpp-language`
Description: Provides Objective-C++ language compilation to Nokee plugins; see the documentation to learn more.
Tags: gradle-native, native, objective-cpp, objcpp, objective-c++, nokee
Website: https://nokee.dev/docs/objective-cpp-language-plugin

### `dev.nokee.objective-c-language`
Description: Provides Objective-C language compilation to Nokee plugins; see the documentation to learn more.
Tags: gradle-native, native, objective-c, objc, nokee
Website: https://nokee.dev/docs/objective-c-language-plugin

### `dev.nokee.jni-library`
Description: Provides support for building Java Native Interface (JNI) libraries supporting Gradle core features; see the documentation to learn more.
Tags: jni, gradle-native, native, cpp, objective-c, objective-cpp, c, nokee
Website: https://nokee.dev/docs/jni-library-plugin

**Comment by lacasseio** [comment]
It's not really a bug, I can't change it. It more of a metadata fix on the portal like plugin ownership change.

**Comment by lacasseio** [comment]
@gradle/core Friendly reminder this is still an issue.

**Comment by big-guy** [comment]
Unless I fat fingered something, this should be done.

I can't add per-version descriptions because these would get reset as soon as you published a new version.

**Comment by lacasseio** [comment]
Thanks, Sterling for this. I really appreciate it. However, it doesn't seem like it got updated in the UI: https://plugins.gradle.org/search?term=dev.nokee

**Comment by big-guy** [comment]
Ah, it did, but I think the sync overwrites it. I think the springboot plugin still publishes to Bintray and they have nice descriptions.  I'll have to look how this is synced.

**Comment by lacasseio** [comment]
Could it work if I only publish the plugin marker to the portal? Or maybe just sync more attributes from bintray?

I guess the root cause for choosing the bintray direction is having control over the artifact. Sometime, the publication fails. With Bintray, I can force publish the binaries. With the portal this is not possible. We can chat more about it if you'd like.

**Comment by lacasseio** [comment]
I will reopen another issue to deal with my plugin as we are migrating away from Bintray and the sync won't be an issue anymore.
