### ISSUE TITLE
Remove plugin org.podval.docbook-gradle-plugin

### ISSUE THREAD

**Issue by dubinsky** [gradle/plugin-portal-requests#42]
### Plugin Id
org.podval.docbook-gradle-plugin

### Current Plugin Owner
- Leonid Dubinsky
- Gradle Plugin Portal: dub
- GitHub: dubinsky

### Context
Plugin moved to `org.opentorah.docbook`.

**Comment by big-guy** [comment]
We really don't like to remove existing plugins unless something is seriously wrong (malware, name squatting).  If your plugin was just moved to a new name, I think it's OK if the old version exists. It might even make sense to publish a new version that emits a message that encourages people to switch.

For that, I'm going to leave the plugins as they are.
