### ISSUE TITLE
Sync with JCenter seems to be broken

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#44]
### Expected Behavior

My newest version, 0.3, is [shown in the plugin portal along with the new plugins](https://plugins.gradle.org/search?term=dev.nokee).

### Current Behavior

My latest plugin version, 0.3, is not shown in the plugin portal along with the new plugins (`dev.nokee.objective-c-ios-application` and `dev.nokee.objective-c-xctest-test-suite`).

### Context

One noteworthy comment is the attributes were set after the artifacts were pushed to Bintray.

### Steps to Reproduce 

Not too sure, I would say publish to Bintray into a repository that is already synced with the plugin portal and tag the attributes required by the portal after?

**Comment by lacasseio** [comment]
Forgot to add, if you use any of the samples https://nokee.dev/docs/current/samples, and keep only the `gradlePluginPortal()` repository in the settings.gradle, the plugins are found without any issue. It seems to be more of a UI/database issue.

**Comment by big-guy** [comment]
@lacasseio which attributes are you referring to?  I'm seeing the bintray sync process looking for the plugin jar to be https://jcenter.bintray.com/dev/nokee/distributions/0.3.0/distributions-0.3.0.jar

If you compare the attributes reported by Bintray:
https://api.bintray.com/packages/gradle/gradle-plugins/dev.nokee:nokee-gradle-plugins/versions/0.3.0/attributes (not working)
https://api.bintray.com/packages/gradle/gradle-plugins/dev.nokee:nokee-gradle-plugins/versions/0.2.0/attributes (working)

Did you upload the plugin in a different way this time?

**Comment by lacasseio** [comment]
Oh... you are so right, my bad for this error. I did move around the publishing part. I fixed it, it should be alright. I will close the issue.
