### ISSUE TITLE
Transfer ownership for com.equisoft.standards.kotlin plugin to equisoft

### ISSUE THREAD

**Issue by Chris-V** [gradle/plugin-portal-requests#45]
### Plugin Id
`com.equisoft.standards.kotlin`

### Current Plugin Owner
`chrisv-equisoft`

### Expected Plugin Owner
`equisoft`

### Context
I created a personal account to deploy our plugin, but I don't 
have any options to set up a business profile. As such I would like to transfer ownership to our business managed account.

Thank you!

**Comment by big-guy** [comment]
@Chris-V This should be done now, please let me know if you have any problems under the new account.
