### ISSUE TITLE
Remove org.kordamp.gradle.kordamp-parentpom:1.16.0

### ISSUE THREAD

**Issue by aalmiray** [gradle/plugin-portal-requests#46]
### Plugin Id
org.kordamp.gradle.kordamp-parentpom 1.16.0

### Current Plugin Owner
aalmiray

### Context
I encountered an error when publishing "org.kordamp.gradle.kordamp-parentpom 1.16.0"

    > Task :publishPlugins
    Could not reuse POM from pluginMaven publication because mavenCoordinates() was used
    Publishing plugin org.kordamp.gradle.kordamp-parentpom version 1.16.0
    Publishing artifact build/libs/kordamp-parentpom-1.16.0.jar
    
    > Task :publishPlugins FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':publishPlugins'.
    > java.net.ConnectException: Operation timed out (Connection timed out)

The network problem may have been on my side. A second attempt led to the following error

    > Task :publishPlugins FAILED
    Could not reuse POM from pluginMaven publication because mavenCoordinates() was used
    Publishing plugin org.kordamp.gradle.kordamp-parentpom version 1.16.0
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':publishPlugins'.
    > Failed to post to server.
      Server responded with:
      Plugin: 'org.kordamp.gradle.kordamp-parentpom', version: '1.16.0' exists already. It was created: 2020-05-30 14:45:37.233

However the GPP lists 1.15.0 as latest. I can't access 1.16.0 to delete it a try again.

Could you delete version 1.16.0 so that I can try a upload again? 
Thank you.

**Comment by big-guy** [comment]
This looks like it was deleted on our side, could you try again and let me know if it's unsuccessful. I can check the logs if there's something else funny going on.

**Comment by aalmiray** [comment]
Thank you. I'll give it a try today.

**Comment by aalmiray** [comment]
Sadly it didn't work

    > Task :publishPlugins FAILED
    Could not reuse POM from pluginMaven publication because mavenCoordinates() was used
    Publishing plugin org.kordamp.gradle.kordamp-parentpom version 1.16.0
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':publishPlugins'.
    > Failed to post to server.
      Server responded with:
      Plugin: 'org.kordamp.gradle.kordamp-parentpom', version: '1.16.0' exists already. It was created: 2020-05-30 14:45:37.233

Previous timestamp is still the same. I think I'm going to skip `1.16.0` and go for another version.
