### ISSUE TITLE
DO NOT APPROVE certain plugins that are pending approval

### ISSUE THREAD

**Issue by Lanchon** [gradle/plugin-portal-requests#47]
please DO NOT APPROVE certain plugin versions that are pending approval.
please DELETE those versions instead. i'll have to republish them.

### Plugin Id
all of `com.github.lanchon.dexpatcher.*`

specifically:
- com.github.lanchon.dexpatcher.apk-library
- com.github.lanchon.dexpatcher.base
- com.github.lanchon.dexpatcher.patched-application
- com.github.lanchon.dexpatcher.patch-library

ONLY DELETE VERSIONS 2.1.0 of these, which are still pending approval.

### Current Plugin Owner
i am

### Context
what else do you need?

**Comment by big-guy** [comment]
This is done.

**Comment by Lanchon** [comment]
thanks so much!
