### ISSUE TITLE
Requesting non-audited access to my plugins

### ISSUE THREAD

**Issue by Lanchon** [gradle/plugin-portal-requests#48]
i used to be able to publish [my plugins](https://plugins.gradle.org/search?term=dexpatcher) without approval, after properly identifying myself to you.

now i'm back to being audited. can this be fixed? i'm running [my own repo](https://dexpatcher.github.io/dexpatcher-repo/) for publishing other related artifacts and it'd make sense for me to move the plugin there if auditing is required for each release.

ideally i'd be authorized to publish under `com.github.lanchon.*` ids.

thanks!

**Comment by big-guy** [comment]
[Since Oct 2018](https://blog.gradle.org/new-plugin-portal-acceptance-criteria), manual approval is required for each group or new plugin id, but not for new versions of already approved plugins/groups.

IOW, once you're approved to use `com.github.lanchon` once, you don't need to be approved again.

**Comment by Lanchon** [comment]
thanks!

**Comment by Lanchon** [comment]
hi again,

please reopen this issue. i deleted the 4 just-published plugins (v2.1.0).

in the past i've published 18 versions of these plugins as artifacts with coordinates:
- com.github.lanchon.dexpatcher:dexpatcher-gradle

i was also able to publish instantly without review.

suddenly all changed...
not only i need review to publish, but the coordinates of my artifacts were (silently) changed, i just noticed:
- **gradle.plugin**.com.github.lanchon.dexpatcher:dexpatcher-gradle

i don't want the coords changed. IMHO, since you accepted the coords before, it seems reasonable to keep accepting them now.

### my question:
- can i be authorized to publish under `com.github.lanchon.*` or `com.github.lanchon.dexpatcher` or `com.github.lanchon.dexpatcher:dexpatcher-gradle` without review and without prepending `gradle.plugin.` to the coords?

if this is no longer possible, i prefer to publish elsewhere.

thanks again for your help.

**Comment by Lanchon** [comment]
please disregard. i've decided on a different course of action. thanks.
