### ISSUE TITLE
No response after a long time

### ISSUE THREAD

**Issue by chenenyu** [gradle/plugin-portal-requests#51]
I have published a plugin 10 days ago, but i didn't get any response. If there  are any mistake in the plugin, i hope to get a feedback via email, or if it's pending approval, the status should be shown in my gradle user homepage.

### Current Behavior

Failed to post to server.
Server responded with:
Plugin: 'com.dycflutter.dfa', version: '0.0.1' exists already. It was created: 2020-06-17 11:35:11.366

**Comment by JLLeitschuh** [comment]
If your plugin upload request was rejected, you should now be able to publish it again.
