### ISSUE TITLE
Transfer ownership from me personally, to a "group"

### ISSUE THREAD

**Issue by sebersole** [gradle/plugin-portal-requests#55]
A number of the plugins I develop are used throughout various builds for the Hibernate team.  Sometimes other members of the team need these plugins published and it would be easier for them to have the ability to publish them themselves.  So we'd like a group for publishing them.

But as the plugin portal does not support groups, I created a `hibernate` "group user".  And would like ownership of some plugins from myself to the group user.

### Plugin Id

* org.hibernate.build.maven-repo-auth
* org.hibernate.build.xjc
* org.hibernate.testing.database-profile

### Current Plugin Owner

sebersole

### Expected Plugin Owner

hibernate

### Context

Not sure what you need here.  The email I associated with the hibernate user is one we use for various team registrations.  You can send an email there if that is what you are looking for.  Or, as I am effectively both sebersole and hibernate you can just use my approval here ;)

**Comment by big-guy** [comment]
Hi @sebersole - sorry I didn't see this issue sooner.

I've transferred the plugins over to the hibernate account. You can now see those plugins under that account: https://plugins.gradle.org/u/hibernate
