### ISSUE TITLE
confirming ownership of gradle.plugin.com.github.theproductiveprogrammer.classlist

### ISSUE THREAD

**Issue by theproductiveprogrammer** [gradle/plugin-portal-requests#58]
Hi,

### Expected Behavior
I would like my plugin approved (gradle.plugin.com.github.theproductiveprogrammer.classlist)

### Current Behavior
Plugin approval is in manual review (with Jonathan Leitschuh)

### Context
As requested I would like to confirm that the email address charles.lobo@gmail.com owns the profile "theproductiveprogrammer" on GitHub. You can see this also via the "author email" of all the commits to the plugin repository:
https://github.com/theproductiveprogrammer/classlist-gradle-plugin

Cheers
Charles (tpp)

**Comment by JLLeitschuh** [comment]
Approved! Thanks!
