### ISSUE TITLE
Add tags `clang-format` and `black` to `com.diffplug.spotless`

### ISSUE THREAD

**Issue by nedtwigg** [gradle/plugin-portal-requests#59]
### Expected Behavior
We added these tags to our plugin [like so](https://github.com/diffplug/spotless/pull/672/files#diff-f704fe1c6781fc1b58996373eca3c0b2), but they didn't show up [when we published](https://plugins.gradle.org/plugin/com.diffplug.spotless).

### Current Behavior

The two new tags `clang-format` and `black` don't show up.

### Context

If someone searches for "clang-format", we want to make sure they know that Spotless can help them.

### Steps to Reproduce 

N/A.

### Your Environment

Here's the [CircleCI build](https://app.circleci.com/pipelines/github/diffplug/spotless/543/workflows/f84503fa-eead-45ae-963b-3170cdc3c67a/jobs/2925).

**Comment by big-guy** [comment]
This is done. let me know if you have any troubles.
