### ISSUE TITLE
Transfer ownership of plugin `no.skatteetaten.gradle.aurora` to `Skatteetaten`

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#6]
### Plugin Id

https://plugins.gradle.org/plugin/no.skatteetaten.gradle.aurora

### Current Plugin Owner

Unknown

### Expected Plugin Owner

Skatteetaten

### Context

See https://discuss.gradle.org/t/transfer-plugin-ownership-skatteetaten/33706

**Comment by Aerlant** [comment]
Verification that this is a valid request. I have asked the current owner/account to verify this aswell.

**Comment by bjartek** [comment]
I am the current owner. How can I verify this?

**Comment by Aerlant** [comment]
When can you resolve this issue?

**Comment by lacasseio** [comment]
Done. @Aerlant should now be the owner. Reopen the issue if there is any problem with publishing a new version.
