### ISSUE TITLE
Improve legacy plugin application snippet

### ISSUE THREAD

**Issue by vpavic** [gradle/plugin-portal-requests#62]
At present, the portal plugin page describes legacy plugin application with repository configuration using explicit Maven URL.
For example, from [`org.gradle.test-retry` plugin page](https://plugins.gradle.org/plugin/org.gradle.test-retry):

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.gradle:test-retry-gradle-plugin:1.1.9"
  }
}

apply plugin: "org.gradle.test-retry"
```

This should be IMO simplified to use `gradlePluginPortal()` instead of `maven { url "https://plugins.gradle.org/m2/" }`.

**Comment by ov7a** [comment]
This is now fixed:

![Image](https://github.com/user-attachments/assets/270080c4-93aa-4a6d-8ae5-5fc52f3965d3)
