### ISSUE TITLE
Change the "main description" of Vaadin plugin

### ISSUE THREAD

**Issue by mstahv** [gradle/plugin-portal-requests#63]
We failed to realise originally how the descriptions work and can't seem to modify the description afterwards, so could you change the "main description" of Vaadin plugin from "Build Vaadin 14 applications with Gradle" to the current we have "Build Vaadin applications with Gradle. Please follow the link below to learn which Plugin version to use with particular Vaadin version. Vaadin recommends using the latest Vaadin LTS version."

Thanks in advance!

**Comment by rieske** [comment]
Done! https://plugins.gradle.org/plugin/com.vaadin
