### ISSUE TITLE
Plugin transfer request

### ISSUE THREAD

**Issue by banderous** [gradle/plugin-portal-requests#64]
### Plugin Id
uk.gov.hmcts.java

### Current Plugin Owner
banderous

### Expected Plugin Owner
hmcts-reform

### Context

Please transfer this to an organisation owned account.

**Comment by big-guy** [comment]
@banderous this should be done. Please let me know if you have any troubles.

Thanks!

**Comment by banderous** [comment]
many thanks @big-guy
