### ISSUE TITLE
publish pending

### ISSUE THREAD

**Issue by wakingrufus** [gradle/plugin-portal-requests#67]
Hi,
I recently published a plugin (https://plugins.gradle.org/plugin/com.github.wakingrufus.swagger)
and it is showing Pending Approval, but I was under the impression that approval was only if I provide a custom group id, which I did not intend to do.
I just want to make sure everything is OK, and please let me know if there is something wrong with the way that I published. It is not my intent to have a custom group.
My source is here: https://github.com/wakingrufus/swagger-gradle-plugin
Thanks

**Comment by JLLeitschuh** [comment]
Hi @wakingrufus,

I'm working through the plugin portal approvals this week. I haven't gotten to yours yet. We're currently holding our world meeting. I'll try to get to your plugin soon.

**Comment by wakingrufus** [comment]
Thanks so much!

**Comment by wakingrufus** [comment]
I'm published thanks!
