### ISSUE TITLE
Plugin artifact uploaded but not activated cause it invisible to public and can't be overriden.

### ISSUE THREAD

**Issue by Him188** [gradle/plugin-portal-requests#68]
### Expected Behavior

New version published successfully and is visible publicly.

### Current Behavior

New version isn't visible in plugin potal. Gradle task `publishPlugins` fails.
```
Failed to post to server.
Server responded with:
Plugin: 'net.mamoe.kotlin-jvm-blocking-bridge', version: '1.4.0' exists already. It was created: 2020-11-08 03:31:05.441
```

### Context

Bad network. The gradle task `publishPlugins` successfully uploaded the artifact but network failed when activating the artifact.

### Your Environment

Gradle 6.7, plugin `com.gradle.plugin-publish` 0.12.0

**Comment by Him188** [comment]
https://plugins.gradle.org/plugin/net.mamoe.kotlin-jvm-blocking-bridge

**Comment by Him188** [comment]
I suggest allowing overriding the artifact if it isn't publicly visible.

**Comment by ljacomet** [comment]
The only time a plugin can be overridden is if it was rejected during the approval process.
Otherwise you have to publish a new version always.
