### ISSUE TITLE
Transfer ownership of `de.europace` namespace to `europace` user

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#7]
### Plugin Id

https://plugins.gradle.org/search?term=de.europace

### Current Plugin Owner

`gesellix`

### Expected Plugin Owner

`europace`

### Context

See https://discuss.gradle.org/t/transfer-plugin-ownership-published-with-wrong-user/33535

**Comment by lacasseio** [comment]
Completed.

**Comment by gesellix** [comment]
Thanks!
