### ISSUE TITLE
How can I update my email address?

### ISSUE THREAD

**Issue by psibre** [gradle/plugin-portal-requests#70]
As a user logged into the Plugins Portal, when I edit my profile, I want to update my email address. However, the email address field is "grayed out" and its value cannot be modified.
How can I update the email address for my plugins portal account?

**Comment by JLLeitschuh** [comment]
Hi @psibre,

We temporarily disabled this feature due to a security concern. We'd like to return functionality here but we don't have a timeline yet. @big-guy can you assist?

**Comment by big-guy** [comment]
I've followed up in a direct email.
