### ISSUE TITLE
Merge two accounts to one

### ISSUE THREAD

**Issue by prgs-gradle** [gradle/plugin-portal-requests#71]
### Plugin Id

progress.openedge.abl
progress.openedge.abl-base
### Current Plugin Owner

progress (aestrada@progress.com)
### Expected Plugin Owner

progresss (prgs-gradle@progress.com)
### Context

The current account is associated with a person, however, since the account belongs to Progress Software we want to move the plugins under an official account with an official email.

If possible I would prefer that these accounts are merged, with username as progress and email as prgs-gradle@progress.com
Otherwise please update the username from progresss to progresssoftware. The new username was a mistake.

**Comment by prgs-gradle** [comment]
I'll appreciate if someone can resolve this.

There was another issue about the inability to change email ID. I suggest that this feature is brought back to allow registered users to have some flexibility and control over their account and published plugins.

Getting these otherwise trivial things done through issues causes significant delay.

**Comment by big-guy** [comment]
I've followed up in a direct email.
