### ISSUE TITLE
Publish a plugin to gradle plugin repository

### ISSUE THREAD

**Issue by sunhao-java** [gradle/plugin-portal-requests#72]
1. I has a plugin named com.lodsve.archetype

2. There is only one version 1.0.0-RELEASE.
![](https://aws1.discourse-cdn.com/gradle/original/2X/9/97bb33890f55897eefb969d03d033feb9435dba1.png)

3. But, when I publish a new version 1.0.1-RELEASE via Intellij IDEA, gradle tell me that:
```
* What went wrong:
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'com.lodsve.archetype', version: '1.0.1-RELEASE' exists already. It was created: 2019-06-15 14:17:06.189
```

4. Why?There is not version ‘1.0.1-RELEASE’ in gradle plugin repository.

**Please help me!**

**Comment by JLLeitschuh** [comment]
Did you previously publish a plugin version `1.0.1-RELEASE` that was deleted?

**Comment by sunhao-java** [comment]
Yes, I had released a version of `1.0.1-RELEASE`, but I've deleted it.
Is it not allowed to release version numbers that have been released before, even if they have been deleted.

Is there any place where I can see the version numbers I have released, including the ones that have been deleted?

**Comment by big-guy** [comment]
@sunhao-java sorry for this getting lost, you should be able to republish versions that have been deleted.  Are you still having this problem?

**Comment by sunhao-java** [comment]
@big-guy I still have this problem. Please take a look at the following exception information:
```
9:43:21: Executing task 'publishPlugins --scan  -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true'...

> Task :compileJava NO-SOURCE
> Task :compileGroovy UP-TO-DATE
> Task :pluginDescriptors UP-TO-DATE
> Task :processResources
> Task :classes
> Task :jar

> Task :groovydoc
Trying to override old definition of task fileScanner

> Task :publishPluginGroovyDocsJar
> Task :publishPluginJar
> Task :javadoc NO-SOURCE
> Task :publishPluginJavaDocsJar

> Task :publishPlugins FAILED
Publishing plugin com.lodsve.archetype version 1.0.1-RELEASE
9 actionable tasks: 7 executed, 2 up-to-date

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/terms-of-service. Do you accept these terms? [yes, no] 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'com.lodsve.archetype', version: '1.0.1-RELEASE' exists already. It was created: 2019-06-15 14:17:06.189

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Comment by big-guy** [comment]
Hmm, this is strange.

I think I've manually removed the previous version now, could you give it another try? Thanks in advance.

**Comment by sunhao-java** [comment]
@big-guy Still the same. My build.gradle:
```
plugins {
    id 'groovy'
    id 'maven'
    id 'signing'
    id "com.gradle.plugin-publish" version "0.12.0"
}

apply plugin: 'groovy'

def env = System.getProperty("profile") ?: "gradle"

apply from: "profile-${env}.gradle"

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}
```

profile-gradle.gradle:
```
apply plugin: 'java-gradle-plugin'
apply plugin: 'maven'

dependencies {
    compile gradleApi()
    compile localGroovy()
}

pluginBundle {
    website = 'https://github.com/lodsve/lodsve-gradle-archetype-plugin'
    vcsUrl = 'https://github.com/lodsve/lodsve-gradle-archetype-plugin'

    description = 'Gradle plugin that generate projects from template.'
    tags = ['archetype', 'template']

    plugins {
        plugin {
            id = 'com.lodsve.archetype'
            displayName = 'Archetype Generate Plugin'
            version = project.version
        }
    }
}
```

settings.gradle
```
group=com.lodsve
version=1.0.1-RELEASE
```

Please help me to see if there is any problem. Thanks very much!

**Comment by ljacomet** [comment]
Could you just publish version 1.0.2-RELEASE?

**Comment by sunhao-java** [comment]
Still failed to publish!

**Comment by ljacomet** [comment]
From looking at the plugin portal internals, you attempted to publish versions a while ago:

| Version | Date |
| --- | --- |
| 1.0.0 | 2019-06-16 04:43:56 |
| 1.0.0-RELEASE | 2019-06-18 03:02:43 |
| 1.0.1-RELEASE | 2021-01-15 06:53:52 |
| 1.0.2-RELEASE | 2020-12-16 07:45:49 |
| 1.0.3-RELEASE | 2020-12-16 07:49:13 |
| 1.1.0-RELEASE | 2020-12-16 07:51:37 |
| 2.0.1-RELEASE | 2020-12-18 08:38:44 |
| 2.0.2-RELEASE | 2020-12-18 08:40:52 |

So I would recommend you make sure your build uses the [latest version of the `plugin-publish` plugin](https://plugins.gradle.org/plugin/com.gradle.plugin-publish) and try a version not yet known by the portal.

All version but `1.0.0-RELEASE` are marked as `Disabled` which usually indicates that something went wrong during publication and artifacts were not properly received.

**Comment by sunhao-java** [comment]
Can I publish the version number marked as `Disabled` ?

**Comment by ljacomet** [comment]
No, not directly. We would need to do some manual cleanup first on the plugin portal.
Is it really not an option to jump to a later version?

**Comment by sunhao-java** [comment]
@ljacomet I just said that, I will try to upgrade the version to release. Thanks very much!
