### ISSUE TITLE
Claim com.epages group

### ISSUE THREAD

**Issue by ozscheyge** [gradle/plugin-portal-requests#73]
When trying to publish https://github.com/ePages-de/restdocs-api-spec ( https://github.com/ePages-de/restdocs-api-spec/pull/80 ) to the plugin portal, we get:
```
> Task :restdocs-api-spec-gradle-plugin:publishPlugins FAILED
Could not reuse POM from pluginMaven publication because mavenCoordinates() was used
Publishing plugin com.epages.restdocs-api-spec version 0.9.9-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':restdocs-api-spec-gradle-plugin:publishPlugins'.
> Failed to post to server.
  Server responded with:
  The user 'epages-dev' does not have write permissions to plugin [com.epages.restdocs-api-spec]
```

### Plugin Id

groupId: `com.epages`
plugin: `com.epages.restdocs-api-spec` (not published on plugin portal, yet)

### Current Plugin Owner

Non-existent or unknown, there is no plugin under the com.epages group:
https://plugins.gradle.org/search?term=com.epages

### Expected Plugin Owner

`epages-dev` https://plugins.gradle.org/u/epages-dev

### Context

The main repository is owned by `ePages-de` organisation on GitHub:
https://github.com/ePages-de/restdocs-api-spec

`epages` organization on bintray:
https://bintray.com/epages
The plugin is already published on bintray:
https://bintray.com/epages/maven/restdocs-api-spec
https://bintray.com/epages/maven/restdocs-api-spec#files/com%2Fepages%2Frestdocs-api-spec-gradle-plugin

I'm a member in both organisations:
https://bintray.com/ozscheyge
https://github.com/orgs/ePages-de/people

**Comment by big-guy** [comment]
Hi @ozscheyge - sorry for this getting lost over the holidays. 

It looks like a plugin was created in 2019, but all of its versions were deleted or never uploaded.

I've cleared that plugin out and reset its ownership information.  You should be able to submit the plugin and it'll show up in our normal approval queue. 

Let me know if you run into any troubles.
