### ISSUE TITLE
Please remove shipkit-auto-version:1.0.0 and shipkit-changelog:1.0.0

### ISSUE THREAD

**Issue by mockitoguy** [gradle/plugin-portal-requests#74]
### Plugin versions to remove

1. org.shipkit:shipkit-auto-version:1.0.0
2. org.shipkit:shipkit-changelog:1.0.0

### Current Plugin Owner

I am the owner

### Context

Those versions were accidentally released few months ago, they are not compatible with anything, they are not functional and they are not used by anyone. If we can get rid of them, we can release functional 1.0.0 versions because we are ready now. If we cannot get rid of them, it will be awkward for us because we would need to publish 2.0.0 as a first major version :(

As a smoke test I searched GitHub and nobody uses those plugins at 1.+ version: https://github.com/search?p=2&q=org.shipkit%3Ashipkit-changelog&type=Code, https://github.com/search?q=org.shipkit%3Ashipkit-auto-version&type=Code

Can you help?

Happy New Year to the Gradle team!

**Comment by mockitoguy** [comment]
Friendly ping!

**Comment by big-guy** [comment]
Hi Szczepan!

It looks like https://plugins.gradle.org/plugin/org.shipkit.shipkit-gh-release is a part of shipkit-changelog, so it would need to be deleted too.

Is that OK?

**Comment by mockitoguy** [comment]
Yes, please! (Just 1.0.0 versions, newer 1.x versions are good.). Thanks!

**Comment by big-guy** [comment]
This should be done now, let me know if you see anything weird.

**Comment by mockitoguy** [comment]
Looks great, thank you!
