### ISSUE TITLE
Update tags request for com.github.sakata1222.jacoco-markdown plugin

### ISSUE THREAD

**Issue by sakata1222** [gradle/plugin-portal-requests#75]
### Plugin Id

`com.github.sakata1222.jacoco-markdown`

### Plugin Owner

`sakata1222`

### Current Tags

- test
- coverage

### Expected Tags

- test
- coverage
- code coverage
- jacoco
- markdown

### Context

Would you add `code coverage`, `jacoco` and `markdown` to tags of the plugin?

**Comment by sakata1222** [comment]
I added a `ownership-transfer` tag unintentionally. This is not `ownership-transfer` request. Please ignore and remove it.

**Comment by big-guy** [comment]
This is done, sorry for the delay.
