### ISSUE TITLE
Remove ru.endlesscode.gradle.bukkit plugin

### ISSUE THREAD

**Issue by osipxd** [gradle/plugin-portal-requests#76]
### Plugin Id

ru.endlesscode.gradle.bukkit

### Current Plugin Owner

Osip Fatkullin (osip.fatkullin@gmail.com)

### Context

New versions of this plugin published with new ID - [ru.endlesscode.bukkitgradle](https://plugins.gradle.org/plugin/ru.endlesscode.bukkitgradle)

**Comment by big-guy** [comment]
@osipxd We generally don't want to delete old plugins because it can break old builds unexpectedly.

I added a "DEPRECATED" message to the old plugin and link to the new one.  Is that good enough?

**Comment by osipxd** [comment]
Ok. Thank you
