### ISSUE TITLE
Please transfer ca.cutterslade.analyze to BigMichi1

### ISSUE THREAD

**Issue by wfhartford** [gradle/plugin-portal-requests#77]
### Plugin Id
ca.cutterslade.analyze

### Current Plugin Owner
wfhartford

### Expected Plugin Owner
BigMichi1

### Context
Michael has been doing much more development on this plugin recently and has offered to take over leadership.

Thank you

**Comment by BigMichi1** [comment]
my profile is https://plugins.gradle.org/u/BigMichi1

**Comment by big-guy** [comment]
This should now be done, let me know if you run into troubles.
