### ISSUE TITLE
Why my plugin group id is misleading?

### ISSUE THREAD

**Issue by anatawa12** [gradle/plugin-portal-requests#80]
The approval request to `com.anatawa12.compile-time-constant` and `com.anatawa12.auto-visitor` are rejected due to 'the plugin group specified could be misleading.'. but the groupId, `com.anatawa12` is my groupid on maven central. why do you think it is misleading?

**Comment by JLLeitschuh** [comment]
Hi @anatawa12,

We need to verify that you own the GroupID by verifying that you own the DNS record. Do you own the `anatawa12.com` domain? If so, can you verify this?

**Comment by anatawa12** [comment]
@JLLeitschuh 
I own `anatawa12.com` and I have the e-mail server for `anatawa12.com` so I want to send an e-mail to verify this domain. Is it ok and where should I send the e-mail to?

**Comment by JLLeitschuh** [comment]
Hi @anatawa12,

The best way to publish under this namespace is to create a Plugin Portal account with your `@anatawa12.com` email address. Are you signing into your Plugin Portal account with GitHub? Which email appears?

**Comment by anatawa12** [comment]
@JLLeitschuh 

I'm signing into the Plugin Portal account with GitHub and my iCloud email address appears in the Portal. So I can't change the e-mail address for Plugin.

**Comment by JLLeitschuh** [comment]
🤔 so, we only use your public GitHub email address. I don't think we use any of the private ones. I think this is a failing on our behalf and a feature we should implement.

**Comment by anatawa12** [comment]
I've added a e-mail address, `github at anatawa12 dot com`, in my profile.

**Comment by anatawa12** [comment]
@JLLeitschuh I added `github@anatawa12.com` in my GitHub profile. Is it required to make it primary?

**Comment by anatawa12** [comment]
They are approved! Thank you!
