### ISSUE TITLE
Remove then approve Gradle plugin: zero88.qwe.gradle.*

### ISSUE THREAD

**Issue by zero88** [gradle/plugin-portal-requests#82]
### Plugin Id

`zero88.qwe.gradle.*`

### Current Plugin Owner

`zero88`

### Context

I reorganized my plugins from `zero88.qwe.gradle.*` to `io.github.zero88.qwe.gradle.*`
Also please help me process these plugin `io.github.zero88.qwe.gradle.*` for using in other projects. I need it ASAP

More question: 
- if version without `-snapshot`, is it auto approval?
- if I use CI workflow to publish `snapshot version` frequently, how can I get rid of `plugin is already existed error`

Thank Gradle team

**Comment by ljacomet** [comment]
I only see the `io.github.zero88.qwe.gradle` plugins on the portal, so I assume that part of the request has been handled.

As for `-SNAPSHOT` versions, their deployment is not supported on the plugin portal.
