### ISSUE TITLE
Transfer ownership of `me.proton` to `protontechnologies`

### ISSUE THREAD

**Issue by techinterviewer** [gradle/plugin-portal-requests#83]
### Plugin Id
https://plugins.gradle.org/plugin/me.proton.detekt
https://plugins.gradle.org/plugin/me.proton.kotlin
https://plugins.gradle.org/plugin/me.proton.publish-plugins
https://plugins.gradle.org/plugin/me.proton.Publish-Plugins ( **Please delete this one** )
https://plugins.gradle.org/plugin/me.proton.tests

### Current Plugin Owner
https://plugins.gradle.org/u/4face

### Expected Plugin Owner
https://plugins.gradle.org/u/protontechnologies

### Context
Published on developer personal account by mistake ( project's gradle.properties has been ignored/misconfigured, so global gradle.properties has been used )

**Comment by 4face-studi0** [comment]
( this is 4face, the developer, as confirmation )

**Comment by big-guy** [comment]
This is done, please open a new issue if you run into any trouble!
