### ISSUE TITLE
Removal request: org.jsonschema2pojo

### ISSUE THREAD

**Issue by eirnym** [gradle/plugin-portal-requests#85]
### Plugin Id

org.jsonschema2pojo

### Current Plugin Owner

https://plugins.gradle.org/u/eirnym

### Context

There was a misunderstanding to publish my plugin under this name. So I want to remove the plugin and publish a new version under old name.

**Comment by ljacomet** [comment]
I do not see this plugin.

Can this be closed?

**Comment by eirnym** [comment]
yes, it can be closed, thank you.
