### ISSUE TITLE
Transfer ownership com.github.eirnym.js2p to jsonschema2dataclass

### ISSUE THREAD

**Issue by eirnym** [gradle/plugin-portal-requests#86]
### Plugin Id

com.github.eirnym.js2p 

### Current Plugin Owner

Arseny Nasokin (me)

### Expected Plugin Owner

jsonschema2dataclass (I'm an admin of the organization)

### Context

I created a GitHub organization for my plugin and want to have old plugin under the same context as the further versions

**Comment by ljacomet** [comment]
Done
