### ISSUE TITLE
Ownership transfer not completed

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#87]
### Plugin Id

All of `dev.gradleplugins` plugins, see original request: https://github.com/gradle/plugin-portal-requests/issues/79

The error I'm seeing is the following:
```
Execution failed for task ':gradle-plugin-development:publishPlugins'.
> Failed to post to server.
  Server responded with:
  The user does not have permission to create a new plugin with ID: dev.gradleplugins.gradle-plugin-functional-test
```

On the online profile, I don't see all of my plugins:
<img width="922" alt="Screen_Shot_2021-03-08_at_4_12_33_PM" src="https://user-images.githubusercontent.com/22181740/110382822-703d1d80-8029-11eb-895b-01ce9aad8553.png">

**Comment by big-guy** [comment]
@lacasseio I think we figured this out over Slack didn't we?
