### ISSUE TITLE
Grant publish permissions for plugin org.ec4j.editorconfig to schowave

### ISSUE THREAD

**Issue by ppalaga** [gradle/plugin-portal-requests#88]
Could please @schowave be allowed to publish org.ec4j.editorconfig **in addition** to me (@ppalaga)?

### Plugin Id
org.ec4j.editorconfig

### Current Plugin Owner
@ppalaga

### Expected Plugin Owner
@ppalaga

### Context
@schowave is our new active community member

**Comment by ljacomet** [comment]
Hi,

For the moment, the Gradle plugin portal only works with a single owner.

Would you have the option of creating a technical account for this?

**Comment by ov7a** [comment]
Closing this issue as stale.
