### ISSUE TITLE
Ownership transfer for dk.kmd.helm.chart.publish from uin_kmd to kmdrd user

### ISSUE THREAD

**Issue by lpiatek** [gradle/plugin-portal-requests#89]
Plugin Id
https://plugins.gradle.org/plugin/dk.kmd.helm.chart.publish

Current Plugin Owner
uin_kmd

Expected Plugin Owner
kmdrd

Context
Created with an incorrect user, we need to use shared company account. 

Regards

**Comment by big-guy** [comment]
Done!
