### ISSUE TITLE
Plugin approval request

### ISSUE THREAD

**Issue by krishnakumar797** [gradle/plugin-portal-requests#90]
I have submitted 4 plugins for the approval, 

- com.rico.platform.dockerRun
- com.rico.platform.roapp
- com.rico.platform.rocommon
- com.rico.platform.swarm

but its still under pending approval. This plugins were already hosted in [bintray](https://bintray.com/tp/rico/ro-app)
Please let me know what needs to be done for the approval.

**Comment by ljacomet** [comment]
Following up over email
