### ISSUE TITLE
More automation and feedback for publishing plugins

### ISSUE THREAD

**Issue by kdabir** [gradle/plugin-portal-requests#91]
### Expected Behavior

When publishing a plugin, either the gradle publishing plugin (local) or the plugin portal itself should list out all the problems that are preventing the plugin from getting published.  For example `invalid group-id`,  `mismatched repo-url` or `verify domain ownership`.  And it should update the feedback automatically when user fixes the problems and publishes the plugin again. Eventually, if all checks are passed, plugin should be published without requiring manual intervention.

### Current Behavior
The current process is manual and does not give user any feedback on where it is blocked and how long will it take. The generic message says 24 hours but it takes way longer than that.

### Context
With precompiled scripts plugin, Gradle should expect more people publishing plugins to the portal.

I tried publishing a plugin (not my first one) but with my org's group id this time. It was not approved for some days so I [dropped a message](https://discuss.gradle.org/t/pending-approval-of-plugins/39512) on the forum as well.

However, I would have liked for it to be automated process so that we can validate the problems with plugin metadata and fix it at once and publish plugins faster.

**Comment by ljacomet** [comment]
I would like more automation as well 😉 and I fully agree that having more validation inside the plugin-publish plugin is one way of providing that.

Sorry that you had to wait this long for feedback.

There will still be a manual step as we would like to provide some protection against (ab)using reverse domain you do not own in groups.

**Comment by ljacomet** [comment]
See https://blog.gradle.org/plugin-portal-validations about progress in this area. Closing as a manual step remains necessary for the first version.
