### ISSUE TITLE
Plugin ownership transfer

### ISSUE THREAD

**Issue by wayne-wu** [gradle/plugin-portal-requests#97]
### Plugin Id

com.yahoo.parsec.gradle-plugin

### Current Plugin Owner

Wayne Wu (wayne.wuuuu@gmail.com)

### Expected Plugin Owner

parsec-maintainers@verizonmedia.com 

### Context

The plugin was created by me back in 2016 when I worked for Yahoo (now part of Verizon Media). They have reached out to me recently to release my ownership so they can modify the plugin.

As proof of ownership, the Gradle account and this Github account should have the same email address.

**Comment by geekybaiyi** [comment]
Hi, Can someone help with this issue ?
@ljacomet ??

**Comment by ljacomet** [comment]
Ownership transfer completed. See https://plugins.gradle.org/plugin/com.yahoo.parsec.gradle-plugin
