### ISSUE TITLE
Continuous Deployment with -SNAPSHOT versions

### ISSUE THREAD

**Issue by jmfayard** [gradle/plugin-portal-requests#98]
Between two releases, it would be super useful for Gradle authors to be able to deploy a public -SNAPSHOT versions to allow for continuous deployment

### Expected Behavior

Like on mavenCentral()

### Current Behavior

No -SNAPSHOT support on gradlePluginsPortal() currently

It's possible to use mavenCentral() for this, but it's more work for both plugin authors and for plugin consumer, who have to configure more things in `pluginManagement { ... } `

### Context

I want to publish snapshot versions of gradle refreshVersions

https://github.com/jmfayard/refreshVersions/issues/340

**Comment by ljacomet** [comment]
We have no plan to offer `-SNAPSHOT` hosting on the portal. Use a different repository for this.
